import React, { createContext, useState, useContext, useEffect, ReactNode } from 'react';

// Language configuration
export const languages = {
  en: {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    flag: '🇺🇸',
    dir: 'ltr' as const
  },
  es: {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    flag: '🇪🇸',
    dir: 'ltr' as const
  },
  fr: {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    flag: '🇫🇷',
    dir: 'ltr' as const
  },
  ha: {
    code: 'ha',
    name: 'Hausa',
    nativeName: 'Hausa',
    flag: '🇳🇬',
    dir: 'ltr' as const
  },
  yo: {
    code: 'yo',
    name: 'Yoruba',
    nativeName: 'Yorùbá',
    flag: '🇳🇬',
    dir: 'ltr' as const
  },
  ig: {
    code: 'ig',
    name: 'Igbo',
    nativeName: 'Igbo',
    flag: '🇳🇬',
    dir: 'ltr' as const
  }
};

// Global translations for the entire app
export const translations = {
  en: {
    // Transactions specific translations
    transactionHistory: 'Transaction History',
    loadingTransactions: 'Loading transactions...',
    noTransactionsYet: 'No transactions yet',
    transactionsWillAppear: 'Your transaction history will appear here',
    transactionDetails: 'Transaction Details',
    type: 'Type',
    asset: 'Asset',
    amount: 'Amount',
    value: 'Value',
    date: 'Date',
    status: 'Status',
    description: 'Description',
    fromAddress: 'From Address',
    transactionFee: 'Transaction Fee',
    
    // Transaction types
    sent: 'Sent',
    received: 'Received',
    swapped: 'Swapped',
    mined: 'Mined',
    crypto: 'Crypto',
    
    // Status types
    completed: 'Completed',
    pending: 'Pending',
    failed: 'Failed',
    
    // Date formats
    unknownDate: 'Unknown date',
    invalidDate: 'Invalid date',

    // Wallets specific translations
    yourWallets: 'Your Wallets',
    loadingYourAssets: 'Loading your assets...',
    withdraw: 'Withdraw',
    requestWithdrawal: 'Request Withdrawal',
    receive: 'Receive',
    generating: 'Generating...',
    exploreDeFi: 'Explore DeFi Opportunities',
    discoverTokens: 'Discover new tokens and high-yield farms in our ecosystem.',
    exploreNow: 'Explore Now',
    adminPrivilegesEnabled: 'Admin privileges enabled',
    loadingUserData: 'Loading user data...',
    minimumBalanceMet: 'Minimum balance requirement met ($6000+)',
    depositHistoryVerified: 'Deposit history verified',
    withdrawalRequirements: 'Requires $6000 minimum balance or deposit history. Contact customer care for guidance.',
    contactSupport: 'Contact Support',
    errorLoadingWalletData: 'Error loading wallet data',
    newAddressGenerated: 'New {coin} address generated!',
    errorGeneratingAddress: 'Error generating wallet address',
    sentSuccessfully: 'Sent Successfully!',
    addressCopied: 'Address Copied!',
    noAddressFound: 'No address found for this coin',
    
    // Modal translations
    send: 'Send',
    withdrawalRequirements: 'Withdrawal Requirements',
    recipientAddress: 'Recipient Address',
    enterAddress: 'Enter {symbol} address',
    amountUSD: 'Amount (USD)',
    confirmSend: 'Confirm Send',
    withdrawalRequirementsDescription: 'To enable withdrawals, you need to meet one of the following conditions:',
    minimumBalanceRequirement: '• Maintain a minimum balance of $6,000 USD if you are a miner',
    makeDepositRequirement: '• Make a deposit into your wallet',
    withdrawalAssistance: 'If you need assistance or have questions about our withdrawal policy, please contact our customer care team in the chat below.',
    close: 'Close',
    shareAddressToReceive: 'Share your address to receive {coin}.',
    generatingAddress: 'Generating address...',
    noAddressAvailable: 'No address available',
    copyAddress: 'Copy Address',
    
    // Form validation
    recipientAddressEmpty: 'Recipient address cannot be empty.',
    enterValidAmount: 'Please enter a valid positive amount.',
    insufficientFunds: 'Insufficient funds for this transaction.',

    // Sidebar
    overview: 'Overview',
    wallets: 'Wallets',
    transactions: 'Transactions',
    mine: 'Mine',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Logout',
    language: 'Language',
    selectLanguage: 'Select Language',
    
    // Common
    welcome: 'Welcome',
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    
    // Overview page
    hello: 'Hello',
    readyToBook: 'Ready to book your next ride in Lagos?',
    myWallet: 'My Wallet',
    totalRides: 'Total Rides',
    rating: 'Rating',
    promoCodes: 'Promo Codes',
    findRide: 'Find a Ride in Lagos',
    enterDestination: 'Enter any Lagos location...',
    findRides: 'Find Rides',
    findingRides: 'Finding Rides...',
    quickActions: 'Quick Actions',
    bookNewRide: 'Book a New Ride',
    scheduleForLater: 'Schedule for Later',
    recentTrips: 'Recent Trips',
    
    // Mine page
    cryptoMining: 'Crypto Mining',
    miningDescription: 'Start mining assets to increase your wallet balance. Mining is simulated and only active while you are on this page. For Faster Mining, Reach out to our customer care for guidance',
    activeMiners: 'Active Miners',
    totalMinedValue: 'Total Mined Value',
    totalCoinsMined: 'Total Coins Mined',
    hashRate: 'Hash Rate',
    price: 'Price',
    loginToMine: 'Login to Mine',
    stopMining: 'Stop Mining',
    startMining: 'Start Mining',
    pleaseLoginToMine: 'Please log in to start mining',
    howMiningWorks: 'How Mining Works',
    miningInstruction1: 'For faster Mining reach out to our customer care or Agents',
    miningInstruction2: 'Mining is simulated and only works while you are on this page',
    miningInstruction3: 'Each mining session adds crypto directly to your wallet',
    miningInstruction4: 'Mined amounts are added to both your specific wallet and total balance',
    miningInstruction5: 'You can mine multiple cryptocurrencies simultaneously',
    miningInstruction6: 'Transactions are auto-saved every 30 seconds for active mining sessions',
    loadingMiningRigs: 'Loading mining rigs...',

    // New Overview page translations
    welcomeToPaycoin: 'Welcome To Paycoin',
    liveTransactions: 'Live Transactions',
    realTimeActivity: 'Real-time user activity',
    liveUpdates: 'Live updates',
    transactionsToday: 'transactions today',
    totalBalance: 'Total Balance',
    portfolioChange24h: '24h Portfolio Change',
    bitcoinBalance: 'Bitcoin Balance',
    activities24h: '24h Activities',
    aiTrading: 'AI Trading',
    automatedTradingDescription: 'Automated trading with intelligent risk management',
    risk: 'RISK',
    currentPrice: 'Current Price',
    h24Change: '24h Change',
    riskLevel: 'Risk Level',
    riskScore: 'Risk Score',
    analyze: 'Analyze',
    activateAITrading: 'Activate AI Trading',
    aiMarketAnalysis: 'AI Market Analysis',
    riskWarning: 'Risk Warning',
    recommendedStrategy: 'Recommended Strategy',
    highRiskStrategy: 'Consider small position sizes and set strict stop-loss orders. Monitor market volatility closely.',
    mediumRiskStrategy: 'Diversify your portfolio and consider dollar-cost averaging. Set take-profit and stop-loss levels.',
    lowRiskStrategy: 'Suitable for gradual accumulation. Consider long-term holding strategy with periodic rebalancing.',
    aiTradingActivated: 'AI Trading Activated!',
    aiBotConnected: 'Your AI trading bot is now connected to your',
    wallet: 'wallet',
    nextStep: 'Next Step',
    depositFundsToStart: 'Deposit funds into your',
    walletToGenerateProfits: 'wallet to start generating profits with AI-powered trading.',
    goToWallet: 'Go to Wallet',
    aiStartTrading: 'Your AI will start trading automatically once funds are available',
    startMiningNow: 'Start Mining Now',
    putHardwareToWork: 'Put your hardware to work and earn crypto rewards.',
    startMining: 'Start Mining',
    recentActivity: 'Recent Activity',
    viewAll: 'View All',
    noRecentActivity: 'No recent activity',
    welcomeBonus: 'Welcome Bonus',
    transaction: 'Transaction',
    upgradeSecurity: 'Upgrade Your Security',
    enable2FADescription: 'Enable Two-Factor Authentication for enhanced protection.',
    secureAccount: 'Secure Account',
    mineEthereum: 'Mine Ethereum',
    mineEthereumDescription: 'Join the network and start mining the second-largest cryptocurrency.',
    viewAllTransactions: 'View All Transactions',
    viewTransactionHistory: 'See your complete transaction history and track all your activities.',
    viewHistory: 'View History',
    bonusAlreadyClaimed: 'Bonus Already Claimed!',
    claim50Bonus: 'Click the button to claim your $50',
    bonusAlreadyClaimedDescription: 'You have already received your welcome bonus. Check your wallet balance!',
    claim50Description: 'Get $50 in BTC by Clicking on the Button NOW!',
    claiming: 'Claiming...',
    bonusClaimed: 'Bonus Claimed ✓',
    claim50Bitcoin: 'Claim $50 worth of Bitcoin',
    failedToClaimBonus: 'Failed to claim bonus',
    failedToClaimBonusTryAgain: 'Failed to claim bonus. Please try again.',
    success: 'Success!',
    youHaveClaimed50: 'You have successfully claimed your $50!',
    bonusAddedDescription: '$50 has been added to your balance and equivalent BTC to your Bitcoin wallet.',
    great: 'Great!',
    justNow: 'Just now',
    minutesAgo: 'm ago',
    hoursAgo: 'h ago',
    daysAgo: 'd ago',
    total: 'total',
    maybeLater: 'Maybe Later'
  },
  es: {
    // Transactions specific translations
    transactionHistory: 'Historial de Transacciones',
    loadingTransactions: 'Cargando transacciones...',
    noTransactionsYet: 'Aún no hay transacciones',
    transactionsWillAppear: 'Tu historial de transacciones aparecerá aquí',
    transactionDetails: 'Detalles de Transacción',
    type: 'Tipo',
    asset: 'Activo',
    amount: 'Cantidad',
    value: 'Valor',
    date: 'Fecha',
    status: 'Estado',
    description: 'Descripción',
    fromAddress: 'Dirección de Origen',
    transactionFee: 'Tarifa de Transacción',
    
    // Transaction types
    sent: 'Enviado',
    received: 'Recibido',
    swapped: 'Intercambiado',
    mined: 'Minado',
    crypto: 'Cripto',
    
    // Status types
    completed: 'Completado',
    pending: 'Pendiente',
    failed: 'Fallido',
    
    // Date formats
    unknownDate: 'Fecha desconocida',
    invalidDate: 'Fecha inválida',

    // Wallets specific translations
    yourWallets: 'Tus Billeteras',
    loadingYourAssets: 'Cargando tus activos...',
    withdraw: 'Retirar',
    requestWithdrawal: 'Solicitar Retiro',
    receive: 'Recibir',
    generating: 'Generando...',
    exploreDeFi: 'Explora Oportunidades DeFi',
    discoverTokens: 'Descubre nuevos tokens y granjas de alto rendimiento en nuestro ecosistema.',
    exploreNow: 'Explorar Ahora',
    adminPrivilegesEnabled: 'Privilegios de administrador habilitados',
    loadingUserData: 'Cargando datos del usuario...',
    minimumBalanceMet: 'Requisito de saldo mínimo cumplido ($6000+)',
    depositHistoryVerified: 'Historial de depósitos verificado',
    withdrawalRequirements: 'Requiere saldo mínimo de $6000 o historial de depósitos. Contacte al servicio al cliente para orientación.',
    contactSupport: 'Contactar Soporte',
    errorLoadingWalletData: 'Error al cargar datos de la billetera',
    newAddressGenerated: '¡Nueva dirección de {coin} generada!',
    errorGeneratingAddress: 'Error al generar dirección de billetera',
    sentSuccessfully: '¡Enviado Exitosamente!',
    addressCopied: '¡Dirección Copiada!',
    noAddressFound: 'No se encontró dirección para esta moneda',
    
    // Modal translations
    send: 'Enviar',
    withdrawalRequirements: 'Requisitos de Retiro',
    recipientAddress: 'Dirección del Destinatario',
    enterAddress: 'Ingrese dirección {symbol}',
    amountUSD: 'Cantidad (USD)',
    confirmSend: 'Confirmar Envío',
    withdrawalRequirementsDescription: 'Para habilitar retiros, debe cumplir una de las siguientes condiciones:',
    minimumBalanceRequirement: '• Mantener un saldo mínimo de $6,000 USD si es minero',
    makeDepositRequirement: '• Realizar un depósito en su billetera',
    withdrawalAssistance: 'Si necesita ayuda o tiene preguntas sobre nuestra política de retiros, contacte a nuestro equipo de servicio al cliente en el chat a continuación.',
    close: 'Cerrar',
    shareAddressToReceive: 'Comparta su dirección para recibir {coin}.',
    generatingAddress: 'Generando dirección...',
    noAddressAvailable: 'No hay dirección disponible',
    copyAddress: 'Copiar Dirección',
    
    // Form validation
    recipientAddressEmpty: 'La dirección del destinatario no puede estar vacía.',
    enterValidAmount: 'Por favor ingrese una cantidad positiva válida.',
    insufficientFunds: 'Fondos insuficientes para esta transacción.',

    // Sidebar
    overview: 'Resumen',
    wallets: 'Billeteras',
    transactions: 'Transacciones',
    mine: 'Minar',
    profile: 'Perfil',
    settings: 'Configuración',
    logout: 'Cerrar Sesión',
    language: 'Idioma',
    selectLanguage: 'Seleccionar Idioma',
    
    // Common
    welcome: 'Bienvenido',
    loading: 'Cargando...',
    save: 'Guardar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    delete: 'Eliminar',
    edit: 'Editar',
    
    // Overview page
    hello: 'Hola',
    readyToBook: '¿Listo para reservar tu próximo viaje en Lagos?',
    myWallet: 'Mi Billetera',
    totalRides: 'Viajes Totales',
    rating: 'Calificación',
    promoCodes: 'Códigos Promo',
    findRide: 'Encuentra un Viaje en Lagos',
    enterDestination: 'Ingresa cualquier ubicación en Lagos...',
    findRides: 'Encontrar Viajes',
    findingRides: 'Buscando Viajes...',
    quickActions: 'Acciones Rápidas',
    bookNewRide: 'Reservar Nuevo Viaje',
    scheduleForLater: 'Programar para Después',
    recentTrips: 'Viajes Recientes',
    
    // Mine page
    cryptoMining: 'Minería de Cripto',
    miningDescription: 'Comienza a minar activos para aumentar tu saldo de billetera. La minería es simulada y solo está activa mientras estás en esta página. Para una minería más rápida, contacta a nuestro servicio al cliente para obtener orientación',
    activeMiners: 'Mineros Activos',
    totalMinedValue: 'Valor Total Minado',
    totalCoinsMined: 'Total de Monedas Minadas',
    hashRate: 'Tasa de Hash',
    price: 'Precio',
    loginToMine: 'Iniciar Sesión para Minar',
    stopMining: 'Detener Minería',
    startMining: 'Comenzar Minería',
    pleaseLoginToMine: 'Por favor inicia sesión para comenzar a minar',
    howMiningWorks: 'Cómo Funciona la Minería',
    miningInstruction1: 'Para una minería más rápida contacta a nuestro servicio al cliente o Agentes',
    miningInstruction2: 'La minería es simulada y solo funciona mientras estás en esta página',
    miningInstruction3: 'Cada sesión de minería agrega cripto directamente a tu billetera',
    miningInstruction4: 'Las cantidades minadas se agregan tanto a tu billetera específica como al saldo total',
    miningInstruction5: 'Puedes minar múltiples criptomonedas simultáneamente',
    miningInstruction6: 'Las transacciones se guardan automáticamente cada 30 segundos para sesiones de minería activas',
    loadingMiningRigs: 'Cargando equipos de minería...',

    // New Overview page translations
    welcomeToPaycoin: 'Bienvenido a Paycoin',
    liveTransactions: 'Transacciones en Vivo',
    realTimeActivity: 'Actividad en tiempo real',
    liveUpdates: 'Actualizaciones en vivo',
    transactionsToday: 'transacciones hoy',
    totalBalance: 'Saldo Total',
    portfolioChange24h: 'Cambio de Portafolio 24h',
    bitcoinBalance: 'Saldo de Bitcoin',
    activities24h: 'Actividades 24h',
    aiTrading: 'Trading con IA',
    automatedTradingDescription: 'Trading automatizado con gestión inteligente de riesgos',
    risk: 'RIESGO',
    currentPrice: 'Precio Actual',
    h24Change: 'Cambio 24h',
    riskLevel: 'Nivel de Riesgo',
    riskScore: 'Puntuación de Riesgo',
    analyze: 'Analizar',
    activateAITrading: 'Activar Trading con IA',
    aiMarketAnalysis: 'Análisis de Mercado con IA',
    riskWarning: 'Advertencia de Riesgo',
    recommendedStrategy: 'Estrategia Recomendada',
    highRiskStrategy: 'Considere tamaños de posición pequeños y establezca órdenes de stop-loss estrictas. Monitoree la volatilidad del mercado de cerca.',
    mediumRiskStrategy: 'Diversifique su cartera y considere el promedio de costo en dólares. Establezca niveles de toma de ganancias y stop-loss.',
    lowRiskStrategy: 'Adecuado para acumulación gradual. Considere una estrategia de tenencia a largo plazo con reequilibrio periódico.',
    aiTradingActivated: '¡Trading con IA Activado!',
    aiBotConnected: 'Tu bot de trading con IA ahora está conectado a tu',
    wallet: 'billetera',
    nextStep: 'Próximo Paso',
    depositFundsToStart: 'Deposita fondos en tu',
    walletToGenerateProfits: 'billetera para comenzar a generar ganancias con trading potenciado por IA.',
    goToWallet: 'Ir a Billetera',
    aiStartTrading: 'Tu IA comenzará a operar automáticamente una vez que haya fondos disponibles',
    startMiningNow: 'Comenzar a Minar Ahora',
    putHardwareToWork: 'Pon tu hardware a trabajar y gana recompensas en cripto.',
    startMining: 'Comenzar a Minar',
    recentActivity: 'Actividad Reciente',
    viewAll: 'Ver Todo',
    noRecentActivity: 'Sin actividad reciente',
    welcomeBonus: 'Bono de Bienvenida',
    transaction: 'Transacción',
    upgradeSecurity: 'Mejorar Seguridad',
    enable2FADescription: 'Habilita la Autenticación de Dos Factores para una protección mejorada.',
    secureAccount: 'Proteger Cuenta',
    mineEthereum: 'Minar Ethereum',
    mineEthereumDescription: 'Únete a la red y comienza a minar la segunda criptomoneda más grande.',
    viewAllTransactions: 'Ver Todas las Transacciones',
    viewTransactionHistory: 'Ve tu historial completo de transacciones y rastrea todas tus actividades.',
    viewHistory: 'Ver Historial',
    bonusAlreadyClaimed: '¡Bono Ya Reclamado!',
    claim50Bonus: 'Haz clic en el botón para reclamar tus $50',
    bonusAlreadyClaimedDescription: 'Ya has recibido tu bono de bienvenida. ¡Revisa tu saldo de billetera!',
    claim50Description: '¡Obtén $50 en BTC haciendo clic en el botón AHORA!',
    claiming: 'Reclamando...',
    bonusClaimed: 'Bono Reclamado ✓',
    claim50Bitcoin: 'Reclamar $50 en Bitcoin',
    failedToClaimBonus: 'Error al reclamar bono',
    failedToClaimBonusTryAgain: 'Error al reclamar bono. Por favor, inténtalo de nuevo.',
    success: '¡Éxito!',
    youHaveClaimed50: '¡Has reclamado exitosamente tus $50!',
    bonusAddedDescription: '$50 se han agregado a tu saldo y BTC equivalente a tu billetera de Bitcoin.',
    great: '¡Genial!',
    justNow: 'Justo ahora',
    minutesAgo: 'm atrás',
    hoursAgo: 'h atrás',
    daysAgo: 'd atrás',
    total: 'total',
    maybeLater: 'Quizás Más Tarde'
  },
  fr: {
    // Transactions specific translations
    transactionHistory: 'Historique des Transactions',
    loadingTransactions: 'Chargement des transactions...',
    noTransactionsYet: 'Aucune transaction pour le moment',
    transactionsWillAppear: 'Votre historique de transactions apparaîtra ici',
    transactionDetails: 'Détails de la Transaction',
    type: 'Type',
    asset: 'Actif',
    amount: 'Montant',
    value: 'Valeur',
    date: 'Date',
    status: 'Statut',
    description: 'Description',
    fromAddress: 'Adresse d\'Expéditeur',
    transactionFee: 'Frais de Transaction',
    
    // Transaction types
    sent: 'Envoyé',
    received: 'Reçu',
    swapped: 'Échangé',
    mined: 'Miné',
    crypto: 'Crypto',
    
    // Status types
    completed: 'Terminé',
    pending: 'En Attente',
    failed: 'Échoué',
    
    // Date formats
    unknownDate: 'Date inconnue',
    invalidDate: 'Date invalide',

    // Wallets specific translations
    yourWallets: 'Vos Portefeuilles',
    loadingYourAssets: 'Chargement de vos actifs...',
    withdraw: 'Retirer',
    requestWithdrawal: 'Demander un Retrait',
    receive: 'Recevoir',
    generating: 'Génération...',
    exploreDeFi: 'Explorer les Opportunités DeFi',
    discoverTokens: 'Découvrez de nouveaux tokens et fermes à haut rendement dans notre écosystème.',
    exploreNow: 'Explorer Maintenant',
    adminPrivilegesEnabled: 'Privilèges administrateur activés',
    loadingUserData: 'Chargement des données utilisateur...',
    minimumBalanceMet: 'Exigence de solde minimum respectée ($6000+)',
    depositHistoryVerified: 'Historique des dépôts vérifié',
    withdrawalRequirements: 'Nécessite un solde minimum de 6000$ ou un historique de dépôts. Contactez le service client pour obtenir des conseils.',
    contactSupport: 'Contacter le Support',
    errorLoadingWalletData: 'Erreur lors du chargement des données du portefeuille',
    newAddressGenerated: 'Nouvelle adresse {coin} générée !',
    errorGeneratingAddress: 'Erreur lors de la génération de l\'adresse du portefeuille',
    sentSuccessfully: 'Envoyé avec Succès !',
    addressCopied: 'Adresse Copiée !',
    noAddressFound: 'Aucune adresse trouvée pour cette pièce',
    
    // Modal translations
    send: 'Envoyer',
    withdrawalRequirements: 'Exigences de Retrait',
    recipientAddress: 'Adresse du Destinataire',
    enterAddress: 'Entrez l\'adresse {symbol}',
    amountUSD: 'Montant (USD)',
    confirmSend: 'Confirmer l\'Envoi',
    withdrawalRequirementsDescription: 'Pour activer les retraits, vous devez remplir l\'une des conditions suivantes :',
    minimumBalanceRequirement: '• Maintenir un solde minimum de 6 000 USD si vous êtes mineur',
    makeDepositRequirement: '• Effectuer un dépôt dans votre portefeuille',
    withdrawalAssistance: 'Si vous avez besoin d\'aide ou avez des questions sur notre politique de retrait, veuillez contacter notre équipe de service client dans le chat ci-dessous.',
    close: 'Fermer',
    shareAddressToReceive: 'Partagez votre adresse pour recevoir {coin}.',
    generatingAddress: 'Génération d\'adresse...',
    noAddressAvailable: 'Aucune adresse disponible',
    copyAddress: 'Copier l\'Adresse',
    
    // Form validation
    recipientAddressEmpty: 'L\'adresse du destinataire ne peut pas être vide.',
    enterValidAmount: 'Veuillez saisir un montant positif valide.',
    insufficientFunds: 'Fonds insuffisants pour cette transaction.',

    // Sidebar
    overview: 'Aperçu',
    wallets: 'Portefeuilles',
    transactions: 'Transactions',
    mine: 'Miner',
    profile: 'Profil',
    settings: 'Paramètres',
    logout: 'Se Déconnecter',
    language: 'Langue',
    selectLanguage: 'Choisir la Langue',
    
    // Common
    welcome: 'Bienvenue',
    loading: 'Chargement...',
    save: 'Sauvegarder',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    delete: 'Supprimer',
    edit: 'Modifier',
    
    // Overview page
    hello: 'Bonjour',
    readyToBook: 'Prêt à réserver votre prochain trajet à Lagos ?',
    myWallet: 'Mon Portefeuille',
    totalRides: 'Trajets Totaux',
    rating: 'Note',
    promoCodes: 'Codes Promo',
    findRide: 'Trouver un Trajet à Lagos',
    enterDestination: 'Entrez n\'importe quel endroit à Lagos...',
    findRides: 'Trouver des Trajets',
    findingRides: 'Recherche de Trajets...',
    quickActions: 'Actions Rapides',
    bookNewRide: 'Réserver un Nouveau Trajet',
    scheduleForLater: 'Planifier pour Plus Tard',
    recentTrips: 'Trajets Récents',
    
    // Mine page
    cryptoMining: 'Mining de Crypto',
    miningDescription: 'Commencez à miner des actifs pour augmenter votre solde de portefeuille. Le minage est simulé et uniquement actif lorsque vous êtes sur cette page. Pour un minage plus rapide, contactez notre service client pour obtenir des conseils',
    activeMiners: 'Mineurs Actifs',
    totalMinedValue: 'Valeur Totale Minée',
    totalCoinsMined: 'Total des Pièces Minées',
    hashRate: 'Taux de Hash',
    price: 'Prix',
    loginToMine: 'Se Connecter pour Miner',
    stopMining: 'Arrêter le Mining',
    startMining: 'Commencer le Mining',
    pleaseLoginToMine: 'Veuillez vous connecter pour commencer à miner',
    howMiningWorks: 'Comment Fonctionne le Mining',
    miningInstruction1: 'Pour un minage plus rapide, contactez notre service client ou nos Agents',
    miningInstruction2: 'Le minage est simulé et ne fonctionne que lorsque vous êtes sur cette page',
    miningInstruction3: 'Chaque session de minage ajoute de la crypto directement à votre portefeuille',
    miningInstruction4: 'Les montants minés sont ajoutés à la fois à votre portefeuille spécifique et au solde total',
    miningInstruction5: 'Vous pouvez miner plusieurs cryptomonnaies simultanément',
    miningInstruction6: 'Les transactions sont enregistrées automatiquement toutes les 30 secondes pour les sessions de minage actives',
    loadingMiningRigs: 'Chargement des équipements de minage...',

    // New Overview page translations
    welcomeToPaycoin: 'Bienvenue sur Paycoin',
    liveTransactions: 'Transactions en Direct',
    realTimeActivity: 'Activité en temps réel',
    liveUpdates: 'Mises à jour en direct',
    transactionsToday: 'transactions aujourd\'hui',
    totalBalance: 'Solde Total',
    portfolioChange24h: 'Changement de Portefeuille 24h',
    bitcoinBalance: 'Solde Bitcoin',
    activities24h: 'Activités 24h',
    aiTrading: 'Trading IA',
    automatedTradingDescription: 'Trading automatisé avec gestion intelligente des risques',
    risk: 'RISQUE',
    currentPrice: 'Prix Actuel',
    h24Change: 'Changement 24h',
    riskLevel: 'Niveau de Risque',
    riskScore: 'Score de Risque',
    analyze: 'Analyser',
    activateAITrading: 'Activer le Trading IA',
    aiMarketAnalysis: 'Analyse de Marché IA',
    riskWarning: 'Avertissement de Risque',
    recommendedStrategy: 'Stratégie Recommandée',
    highRiskStrategy: 'Envisagez des tailles de position réduites et définissez des ordres de stop-loss stricts. Surveillez attentivement la volatilité du marché.',
    mediumRiskStrategy: 'Diversifiez votre portefeuille et envisagez la moyenne de coût. Définissez des niveaux de prise de bénéfices et de stop-loss.',
    lowRiskStrategy: 'Convient pour une accumulation progressive. Envisagez une stratégie de détention à long terme avec rééquilibrage périodique.',
    aiTradingActivated: 'Trading IA Activé !',
    aiBotConnected: 'Votre bot de trading IA est maintenant connecté à votre',
    wallet: 'portefeuille',
    nextStep: 'Prochaine Étape',
    depositFundsToStart: 'Déposez des fonds dans votre',
    walletToGenerateProfits: 'portefeuille pour commencer à générer des profits avec le trading assisté par IA.',
    goToWallet: 'Aller au Portefeuille',
    aiStartTrading: 'Votre IA commencera à trader automatiquement une fois les fonds disponibles',
    startMiningNow: 'Commencer à Miner Maintenant',
    putHardwareToWork: 'Mettez votre matériel au travail et gagnez des récompenses en crypto.',
    startMining: 'Commencer à Miner',
    recentActivity: 'Activité Récente',
    viewAll: 'Voir Tout',
    noRecentActivity: 'Aucune activité récente',
    welcomeBonus: 'Bonus de Bienvenue',
    transaction: 'Transaction',
    upgradeSecurity: 'Améliorer la Sécurité',
    enable2FADescription: 'Activez l\'Authentification à Deux Facteurs pour une protection renforcée.',
    secureAccount: 'Sécuriser le Compte',
    mineEthereum: 'Miner Ethereum',
    mineEthereumDescription: 'Rejoignez le réseau et commencez à miner la deuxième plus grande cryptomonnaie.',
    viewAllTransactions: 'Voir Toutes les Transactions',
    viewTransactionHistory: 'Consultez votre historique complet de transactions et suivez toutes vos activités.',
    viewHistory: 'Voir l\'Historique',
    bonusAlreadyClaimed: 'Bonus Déjà Réclamé !',
    claim50Bonus: 'Cliquez sur le bouton pour réclamer vos 50$',
    bonusAlreadyClaimedDescription: 'Vous avez déjà reçu votre bonus de bienvenue. Vérifiez votre solde de portefeuille !',
    claim50Description: 'Obtenez 50$ en BTC en cliquant sur le bouton MAINTENANT !',
    claiming: 'En cours de réclamation...',
    bonusClaimed: 'Bonus Réclamé ✓',
    claim50Bitcoin: 'Réclamer 50$ en Bitcoin',
    failedToClaimBonus: 'Échec de la réclamation du bonus',
    failedToClaimBonusTryAgain: 'Échec de la réclamation du bonus. Veuillez réessayer.',
    success: 'Succès !',
    youHaveClaimed50: 'Vous avez réussi à réclamer vos 50$ !',
    bonusAddedDescription: '50$ ont été ajoutés à votre solde et l\'équivalent en BTC à votre portefeuille Bitcoin.',
    great: 'Super !',
    justNow: 'À l\'instant',
    minutesAgo: 'min',
    hoursAgo: 'h',
    daysAgo: 'j',
    total: 'total',
    maybeLater: 'Peut-être Plus Tard'
  },
  ha: {
    // Transactions specific translations
    transactionHistory: 'Tarihin Ma\'amaloli',
    loadingTransactions: 'Ana loda ma\'amaloli...',
    noTransactionsYet: 'Babu ma\'amaloli tukuna',
    transactionsWillAppear: 'Tarihin ma\'amalolin ku zai bayyana a nan',
    transactionDetails: 'Cikakkun Bayanan Ma\'amala',
    type: 'Nau\'i',
    asset: 'Kadara',
    amount: 'Adadi',
    value: 'Ƙima',
    date: 'Kwanan wata',
    status: 'Matsayi',
    description: 'Bayani',
    fromAddress: 'Adireshin Maɗaukaki',
    transactionFee: 'Kuɗin Ma\'amala',
    
    // Transaction types
    sent: 'Aika',
    received: 'Karɓa',
    swapped: 'Canja',
    mined: 'An Haka',
    crypto: 'Kudin Sirri',
    
    // Status types
    completed: 'An Kammala',
    pending: 'Ana Jira',
    failed: 'Ya Gaza',
    
    // Date formats
    unknownDate: 'Ranar da ba a sani ba',
    invalidDate: 'Ranar mara inganci',

    // Wallets specific translations
    yourWallets: 'Walat ɗinku',
    loadingYourAssets: 'Ana loda kadarorinku...',
    withdraw: 'Cire',
    requestWithdrawal: 'Neman Cirewa',
    receive: 'Karɓa',
    generating: 'Ana ƙirƙira...',
    exploreDeFi: 'Bincika Damar DeFi',
    discoverTokens: 'Gano sabbin tokens da manyan gonaki a cikin tsarin mu.',
    exploreNow: 'Bincika Yanzu',
    adminPrivilegesEnabled: 'An kunna gatan admin',
    loadingUserData: 'Ana loda bayanan mai amfani...',
    minimumBalanceMet: 'An cika buƙatun ma\'auni mafi ƙanƙanta ($6000+)',
    depositHistoryVerified: 'An tabbatar da tarihin ajiya',
    withdrawalRequirements: 'Yana buƙatar ma\'auni mafi ƙanƙanta na $6000 ko tarihin ajiya. Tuntuɓi kulawar abokin ciniki don jagora.',
    contactSupport: 'Tuntuɓi Tallafi',
    errorLoadingWalletData: 'Kuskuren loda bayanan walat',
    newAddressGenerated: 'An ƙirƙiri sabon adireshin {coin}!',
    errorGeneratingAddress: 'Kuskuren ƙirƙiran adireshin walat',
    sentSuccessfully: 'An Aika da Nasarar!',
    addressCopied: 'An Kwafi Adireshin!',
    noAddressFound: 'Babu adireshin da aka samu don wannan tsabar kudin',
    
    // Modal translations
    send: 'Aika',
    withdrawalRequirements: 'Bukatun Cirewa',
    recipientAddress: 'Adireshin Mai Karɓa',
    enterAddress: 'Shigar da adireshin {symbol}',
    amountUSD: 'Adadin (USD)',
    confirmSend: 'Tabbatar Aikawa',
    withdrawalRequirementsDescription: 'Don kunna cirewa, kuna buƙatar cika ɗaya daga cikin sharuɗɗan masu zuwa:',
    minimumBalanceRequirement: '• Kula da ma\'auni mafi ƙanƙanta na $6,000 USD idan kuna ma\'aikacin hakar ma\'adinai',
    makeDepositRequirement: '• Yi ajiya a cikin walat ɗin ku',
    withdrawalAssistance: 'Idan kuna buƙatar taimako ko kuna da tambayoyi game da manufar mu ta cirewa, da fatan za a tuntuɓi ƙungiyar mu ta kulawar abokin ciniki a cikin tattaunawar da ke ƙasa.',
    close: 'Rufe',
    shareAddressToReceive: 'Raba adireshin ku don karɓar {coin}.',
    generatingAddress: 'Ana ƙirƙiran adireshi...',
    noAddressAvailable: 'Babu adireshin da ake samu',
    copyAddress: 'Kwafi Adireshin',
    
    // Form validation
    recipientAddressEmpty: 'Adireshin mai karɓa ba zai iya zama fanko ba.',
    enterValidAmount: 'Don Allah shigar da ingantaccen adadi mai kyau.',
    insufficientFunds: 'Kudi bai isa ba don wannan ma\'amala.',

    // Sidebar
    overview: 'Duba',
    wallets: 'Walat',
    transactions: 'Maamaloli',
    mine: 'Hako',
    profile: 'Bayanin Kai',
    settings: 'Saituna',
    logout: 'Fita',
    language: 'Harshe',
    selectLanguage: 'Zaɓi Harshe',
    
    // Common
    welcome: 'Barka da zuwa',
    loading: 'Ana loda...',
    save: 'Ajiye',
    cancel: 'Soke',
    confirm: 'Tabbatar',
    delete: 'Share',
    edit: 'Gyara',
    
    // Overview page
    hello: 'Sannu',
    readyToBook: 'Shirye kake don yin haya a Lagos?',
    myWallet: 'Walati Na',
    totalRides: 'Jimlar Haya',
    rating: 'Kima',
    promoCodes: 'Lambobin Tallan',
    findRide: 'Nemo Haya a Lagos',
    enterDestination: 'Shigar da kowane wuri a Lagos...',
    findRides: 'Nemo Haya',
    findingRides: 'Ana Neman Haya...',
    quickActions: 'Ayyuka Maimaitawa',
    bookNewRide: 'Yi Sabon Haya',
    scheduleForLater: 'Shirya Don Gobe',
    recentTrips: 'Haya Kwanan Nan',
    
    // Mine page
    cryptoMining: 'Hakar Kudi na Sirri',
    miningDescription: 'Fara hakar kadarori don ƙara ma\'aunin walat ɗin ku. Hakar kwaikwayo ce kuma tana aiki ne kawai yayin da kuke kan wannan shafi. Don Hakar Sauri, Tuntuɓi kulawar abokin ciniki don jagora',
    activeMiners: 'Masu Haka Aiki',
    totalMinedValue: 'Jimlar Ƙimar Hakar',
    totalCoinsMined: 'Jimlar Kudaden da aka Haka',
    hashRate: 'Adadin Hash',
    price: 'Farashin',
    loginToMine: 'Shiga Don Haka',
    stopMining: 'Daina Hakar',
    startMining: 'Fara Hakar',
    pleaseLoginToMine: 'Don Allah shiga don fara hakar',
    howMiningWorks: 'Yadda Hakar ke Aiki',
    miningInstruction1: 'Don hakar sauri tuntuɓi kulawar abokin ciniki ko Wakilai',
    miningInstruction2: 'Hakar kwaikwayo ce kuma tana aiki ne kawai yayin da kuke kan wannan shafi',
    miningInstruction3: 'Kowane zaman haka yana ƙara kudin sirri kai tsaye zuwa walat ɗin ku',
    miningInstruction4: 'Adadin da aka haka ana ƙara su zuwa walat ɗin ku na musamman da jimlar ma\'auni',
    miningInstruction5: 'Kuna iya hakar kudaden sirri da yawa lokaci guda',
    miningInstruction6: 'Ana adana ma\'amaloli kai tsaye kowane daƙiƙa 30 don zaman hakar aiki',
    loadingMiningRigs: 'Ana loda kayan aikin hakar...',

    // New Overview page translations
    welcomeToPaycoin: 'Barka da zuwa Paycoin',
    liveTransactions: 'Ma\'amaloli Kai Tsaye',
    realTimeActivity: 'Ayyuka na lokaci gaskiya',
    liveUpdates: 'Sabuntawa kai tsaye',
    transactionsToday: 'ma\'amaloli yau',
    totalBalance: 'Jimlar Ma\'auni',
    portfolioChange24h: 'Canjin Fayil 24h',
    bitcoinBalance: 'Ma\'aunin Bitcoin',
    activities24h: 'Ayyuka 24h',
    aiTrading: 'Cinayar AI',
    automatedTradingDescription: 'Cinayar ta atomatik tare da sarrafa hadarin wayo',
    risk: 'HADARI',
    currentPrice: 'Farashin Na Yanzu',
    h24Change: 'Canjin 24h',
    riskLevel: 'Matakin Hadari',
    riskScore: 'Makin Hadari',
    analyze: 'Bincika',
    activateAITrading: 'Kunna Cinayar AI',
    aiMarketAnalysis: 'Binciken Kasuwa na AI',
    riskWarning: 'Gargadin Hadari',
    recommendedStrategy: 'Dabarar da Aka Ba da Shawara',
    highRiskStrategy: 'Yi la\'akari da ƙananan girman matsayi kuma saita umarnin dakatar da asara mai tsauri. Sa ido kan saurin canjin kasuwa sosai.',
    mediumRiskStrategy: 'Rarraba fayil ɗin ku kuma yi la\'akari da matsakaicin farashin dala. Saita matakan samun riba da dakatar da asara.',
    lowRiskStrategy: 'Ya dace don tarawa a hankali. Yi la\'akari da dabarun riƙe na dogon lokaci tare da daidaitawa na lokaci-lokaci.',
    aiTradingActivated: 'Cinayar AI An Kunna!',
    aiBotConnected: 'Bot ɗin cinayar AI ɗin ku yanzu yana haɗe da',
    wallet: 'walat ɗin ku',
    nextStep: 'Mataki Na Gaba',
    depositFundsToStart: 'Ajiye kuɗi a cikin',
    walletToGenerateProfits: 'walat ɗin ku don fara samar da riba tare da cinayar da AI ke tallafawa.',
    goToWallet: 'Je Walat',
    aiStartTrading: 'AI ɗin ku zai fara cinayar ta atomatik da zarar an sami kuɗi',
    startMiningNow: 'Fara Haka Yanzu',
    putHardwareToWork: 'Sanya kayan aikin ku yin aiki kuma ku sami ladan kuɗin sirri.',
    startMining: 'Fara Haka',
    recentActivity: 'Aiki Kwanan Nan',
    viewAll: 'Duba Duka',
    noRecentActivity: 'Babu aiki kwanan nan',
    welcomeBonus: 'Kyautar Maraba',
    transaction: 'Ma\'amala',
    upgradeSecurity: 'Haɓaka Tsaro',
    enable2FADescription: 'Kunna Tabbatar da Abokan Biyu Don Ƙarin Kariya.',
    secureAccount: 'Tsare Asusu',
    mineEthereum: 'Haka Ethereum',
    mineEthereumDescription: 'Shiga cikin hanyar sadarwa kuma fara haka kudin sirri na biyu mafi girma.',
    viewAllTransactions: 'Duba Duk Ma\'amaloli',
    viewTransactionHistory: 'Dubi cikakken tarihin ma\'amalolin ku kuma ku bi duk ayyukan ku.',
    viewHistory: 'Duba Tarihi',
    bonusAlreadyClaimed: 'An riga an yi iƙirarin Kyauta!',
    claim50Bonus: 'Danna maɓallin don neman $50 ɗin ku',
    bonusAlreadyClaimedDescription: 'Kun riga kun karɓi kyautar maraba. Duba ma\'aunin walat ɗin ku!',
    claim50Description: 'Samu $50 a cikin BTC ta Danna Maɓallin YANZU!',
    claiming: 'Ana nema...',
    bonusClaimed: 'An yi iƙirarin Kyauta ✓',
    claim50Bitcoin: 'Yi iƙirarin $50 a cikin Bitcoin',
    failedToClaimBonus: 'Kasa yin iƙirarin kyauta',
    failedToClaimBonusTryAgain: 'Kasa yin iƙirarin kyauta. Don Allah a sake gwadawa.',
    success: 'Nasara!',
    youHaveClaimed50: 'Kun yi nasarar neman $50 ɗin ku!',
    bonusAddedDescription: 'An ƙara $50 zuwa ma\'aunin ku daidai da BTC zuwa walat ɗin ku na Bitcoin.',
    great: 'Mai Kyau!',
    justNow: 'Yanzu yanzu',
    minutesAgo: 'm da suka wuce',
    hoursAgo: 'h da suka wuce',
    daysAgo: 'k da suka wuce',
    total: 'jimla',
    maybeLater: 'Wataƙila Daga Baya'
  },
  yo: {
    // Transactions specific translations
    transactionHistory: 'Itan Iṣẹṣiro',
    loadingTransactions: 'O n loọdu awọn iṣẹṣiro...',
    noTransactionsYet: 'Ko si iṣẹṣiro sibẹsibẹ',
    transactionsWillAppear: 'Itan iṣẹṣiro rẹ yoo han nibi',
    transactionDetails: 'Awọn Alaye Iṣẹṣiro',
    type: 'Iru',
    asset: 'Ẹru',
    amount: 'Iye',
    value: 'Iye-ori',
    date: 'Ọjọ',
    status: 'Ipo',
    description: 'Apejuwe',
    fromAddress: 'Adirẹsi Lati',
    transactionFee: 'Owo Owo Iṣẹṣiro',
    
    // Transaction types
    sent: 'Ti firanṣẹ',
    received: 'Ti gba',
    swapped: 'Ti paṣipaarọ',
    mined: 'Ti Gba',
    crypto: 'Crypto',
    
    // Status types
    completed: 'Ti pari',
    pending: 'Iṣẹyọ',
    failed: 'Ti kuna',
    
    // Date formats
    unknownDate: 'Ọjọ aimọ',
    invalidDate: 'Ọjọ ailọwọ',

    // Wallets specific translations
    yourWallets: 'Awọn Apamọwọ Rẹ',
    loadingYourAssets: 'O n loọdu awọn ẹru rẹ...',
    withdraw: 'Yọ',
    requestWithdrawal: 'Beere Yiyọ',
    receive: 'Gba',
    generating: 'O n ṣẹda...',
    exploreDeFi: 'Ṣe Iwadi Awọn Anfaani DeFi',
    discoverTokens: 'Ṣe awari awọn titoka tuntun ati awọn oko-oko oloyun ni ile wa.',
    exploreNow: 'Ṣe Iwadi Ni Bayi',
    adminPrivilegesEnabled: 'Awọn anfani admin ti mu ṣiṣẹ',
    loadingUserData: 'O n loọdu data olumulo...',
    minimumBalanceMet: 'Ofin iwọn o kere ti ni idinku ($6000+)',
    depositHistoryVerified: 'Itan idokowo ti jẹrisi',
    withdrawalRequirements: 'Nilo iwọn o kere ti $6000 tabi itan idokowo. Kan si itọju onibara wa fun itọsọna.',
    contactSupport: 'Kan si Atilẹyin',
    errorLoadingWalletData: 'Aṣiṣe loọdu data apamọwọ',
    newAddressGenerated: 'Adirẹsi {coin} tuntun ti ṣẹda!',
    errorGeneratingAddress: 'Aṣiṣe ṣiṣẹda adirẹsi apamọwọ',
    sentSuccessfully: 'A ti Firanṣẹ ni Aṣeyọri!',
    addressCopied: 'Adirẹsi ti Dakọ!',
    noAddressFound: 'Ko si adirẹsi ti a ri fun owo yii',
    
    // Modal translations
    send: 'Firanṣẹ',
    withdrawalRequirements: 'Awọn Ofin Yiyọ',
    recipientAddress: 'Adirẹsi Olugba',
    enterAddress: 'Tẹ adirẹsi {symbol}',
    amountUSD: 'Iye (USD)',
    confirmSend: 'Jẹrisi Firanṣẹ',
    withdrawalRequirementsDescription: 'Lati mu yiyọ ṣiṣẹ, o nilo lati pade ọkan ninu awọn ofin wọnyi:',
    minimumBalanceRequirement: '• Ṣetọju iwọn o kere ti $6,000 USD ti o ba jẹ olugba-okuta',
    makeDepositRequirement: '• Ṣe idokowo si apamọwọ rẹ',
    withdrawalAssistance: 'Ti o ba nilo iranlọwọ tabi o ni awọn ibeere nipa ilana wa ti yiyọ, jọwọ kan si egbe itọju onibara wa ninu ajọjọ isalẹ.',
    close: 'Pa',
    shareAddressToReceive: 'Pin adirẹsi rẹ lati gba {coin}.',
    generatingAddress: 'O n ṣẹda adirẹsi...',
    noAddressAvailable: 'Ko si adirẹsi ti o wa',
    copyAddress: 'Dakọ Adirẹsi',
    
    // Form validation
    recipientAddressEmpty: 'Adirẹsi olugba ko le jẹ ofo.',
    enterValidAmount: 'Jọwọ tẹ iye ti o dara sii.',
    insufficientFunds: 'Ko si owo to si fun iṣẹṣiro yii.',

    // Sidebar
    overview: 'Akopọ',
    wallets: 'Apamọwọ',
    transactions: 'Iṣẹṣiro',
    mine: 'Mi',
    profile: 'Profaili',
    settings: 'Etọ',
    logout: 'Jade',
    language: 'Ede',
    selectLanguage: 'Yan Ede',
    
    // Common
    welcome: 'Kaabo',
    loading: 'O n loọdu...',
    save: 'Fipamọ',
    cancel: 'Fagilee',
    confirm: 'Jẹrisi',
    delete: 'Paarẹ',
    edit: 'Ṣatunkọ',
    
    // Overview page
    hello: 'Pẹlẹ',
    readyToBook: 'Ṣetan lati yẹ iṣẹ rẹ ti o n bọ ni Lagos?',
    myWallet: 'Apamọwọ Mi',
    totalRides: 'Lapapọ Iṣẹ',
    rating: 'Iwọn',
    promoCodes: 'Awọn koodu Ipolongo',
    findRide: 'Wa Iṣẹ kan ni Lagos',
    enterDestination: 'Tẹ ibikibi ni Lagos...',
    findRides: 'Wa Awọn Iṣẹ',
    findingRides: 'N wa Awọn Iṣẹ...',
    quickActions: 'Awọn Iṣẹ Kia',
    bookNewRide: 'Yẹ Iṣẹ Tuntun',
    scheduleForLater: 'Yẹda Fun Lẹẹkansi',
    recentTrips: 'Awọn Iṣẹ Laipe',
    
    // Mine page
    cryptoMining: 'Gbigba Crypto',
    miningDescription: 'Bẹrẹ gbigba ẹru lati pọkun iwọn apamọwọ rẹ. Gbigba jẹ iṣẹlẹ atunṣe ati pe o nṣiṣẹ nikan nigbati o ba wa ni ojúewé yii. Fun Gbigba Yara, Darapọ mọ itọju onibara wa fun itọsọna',
    activeMiners: 'Awọn Olugba Ti nṣiṣẹ',
    totalMinedValue: 'Lapapọ Iye Gbigba',
    totalCoinsMined: 'Lapapọ Awọn Owo Gbigba',
    hashRate: 'Iwọn Hash',
    price: 'Iye',
    loginToMine: 'Wọle Lati Gba',
    stopMining: 'Duro Gbigba',
    startMining: 'Bẹrẹ Gbigba',
    pleaseLoginToMine: 'Jọwọ wọle lati bẹrẹ gbigba',
    howMiningWorks: 'Bawo ni Gbigba Ṣe nṣiṣẹ',
    miningInstruction1: 'Fun gbigba yara darapọ mọ itọju onibara wa tabi Awọn Aṣoju',
    miningInstruction2: 'Gbigba jẹ iṣẹlẹ atunṣe ati pe o nṣiṣẹ nikan nigbati o ba wa ni ojúewé yii',
    miningInstruction3: 'Gbogbo akoko gbigba nfi crypto taara si apamọwọ rẹ',
    miningInstruction4: 'Awọn iye ti a gba nfi kun apamọwọ rẹ pato ati lapapọ iwọn',
    miningInstruction5: 'O le gba ọpọlọpọ cryptocurrencies ni akoko kan',
    miningInstruction6: 'Awọn iṣẹṣiro nfipamọ taara ni gbogbo aaya 30 fun awọn akoko gbigba ti nṣiṣẹ',
    loadingMiningRigs: 'O n loọdu awọn ẹrọ gbigba...',

    // New Overview page translations
    welcomeToPaycoin: 'Kaabo si Paycoin',
    liveTransactions: 'Awọn Iṣẹṣiro Lailẹgbẹ',
    realTimeActivity: 'Iṣẹṣiro igba otitọ',
    liveUpdates: 'Awọn imudojuiwọn lailẹgbẹ',
    transactionsToday: 'awọn iṣẹṣiro loni',
    totalBalance: 'Lapapọ Iwọn',
    portfolioChange24h: 'Iyipada Portfolio 24h',
    bitcoinBalance: 'Iwọn Bitcoin',
    activities24h: 'Awọn Iṣẹ 24h',
    aiTrading: 'Titaja AI',
    automatedTradingDescription: 'Titaja aifọwọyi pẹlu iṣakoso ewu oye',
    risk: 'EWU',
    currentPrice: 'Iye Lọwọlọwọ',
    h24Change: 'Iyipada 24h',
    riskLevel: 'Ipele Ewu',
    riskScore: 'Iwọn Ewu',
    analyze: 'Ṣe iwadi',
    activateAITrading: 'Mu Titaja AI Ṣiṣẹ',
    aiMarketAnalysis: 'Iwadi Oja AI',
    riskWarning: 'Ikilo Ewu',
    recommendedStrategy: 'Ilana Imọran',
    highRiskStrategy: 'Ṣe akiyesi iwọn ipo kekere ki o fi awọn aṣẹ idaduro-padanu le ṣe. Ṣe abojuto iyipada oja ni ṣiṣe.',
    mediumStrategy: 'Yatọ portfolio rẹ ki o ṣe akiyesi apapọ iye dola. Fi awọn ipele gbigba-anfani ati idaduro-padanu ṣeto.',
    lowRiskStrategy: 'Yẹ fun ikunṣe diẹ diẹ. Ṣe akiyesi ilana titojọ igba-ọna pẹlu iṣọdọtun akoko.',
    aiTradingActivated: 'Titaja AI Ti Mu Ṣiṣẹ!',
    aiBotConnected: 'Bot titaja AI rẹ ti sopọ mọ',
    wallet: 'apamọwọ rẹ',
    nextStep: 'Igbesẹ Iwọle',
    depositFundsToStart: 'Fi awọn owo si',
    walletToGenerateProfits: 'apamọwọ rẹ lati bẹrẹ ṣiṣẹda ẹsan pẹlu titaja ti AI nṣe atilẹyin.',
    goToWallet: 'Lọ si Apamọwọ',
    aiStartTrading: 'AI rẹ yoo bẹrẹ titaja laifọwọyi ni kete ti owo ba wa',
    startMiningNow: 'Bẹrẹ Gbigba Ni Bayi',
    putHardwareToWork: 'Fi ẹrọ rẹ ṣiṣẹ ki o jẹ awọn ẹsan crypto.',
    startMining: 'Bẹrẹ Gbigba',
    recentActivity: 'Iṣẹ Laipe',
    viewAll: 'Wo Gbogbo',
    noRecentActivity: 'Ko si iṣẹ laipe',
    welcomeBonus: 'Bonusi Ikẹkọ',
    transaction: 'Iṣẹṣiro',
    upgradeSecurity: 'Ṣe agbekalẹ Aabo',
    enable2FADescription: 'Mu Ijẹrisi Meji Ṣiṣẹ Fun Aabo ti o ni ilọsiwaju.',
    secureAccount: 'Aabo Iroyin',
    mineEthereum: 'Gba Ethereum',
    mineEthereumDescription: 'Darapọ mọ nẹtiwọọki ki o bẹrẹ gbigba crypto keji tobi julọ.',
    viewAllTransactions: 'Wo Gbogbo Awọn Iṣẹṣiro',
    viewTransactionHistory: 'Wo itan iṣẹṣiro rẹ kikun ki o tẹle gbogbo awọn iṣẹ rẹ.',
    viewHistory: 'Wo Itan',
    bonusAlreadyClaimed: 'Bonusi Ti Gba Tẹlẹ!',
    claim50Bonus: 'Tẹ bọtini lati gba $50 rẹ',
    bonusAlreadyClaimedDescription: 'O ti gba bonusi ikẹkọ rẹ tẹlẹ. Ṣayẹwo iwọn apamọwọ rẹ!',
    claim50Description: 'Gba $50 ni BTC nipasẹ Tite Bọtini NI BAYI!',
    claiming: 'N gba...',
    bonusClaimed: 'Bonusi Ti Gba ✓',
    claim50Bitcoin: 'Gba $50 ni Bitcoin',
    failedToClaimBonus: 'Kuna lati gba bonusi',
    failedToClaimBonusTryAgain: 'Kuna lati gba bonusi. Jọwọ gbiyanju lẹẹkansi.',
    success: 'Aṣeyọri!',
    youHaveClaimed50: 'O ti gba $50 rẹ ni aṣeyọri!',
    bonusAddedDescription: 'A ti fi $50 kun iwọn rẹ ati Bitcoin dogba si apamọwọ Bitcoin rẹ.',
    great: 'Pẹlu!',
    justNow: 'Ni bayi',
    minutesAgo: 'iṣẹju sẹyin',
    hoursAgo: 'wakati sẹyin',
    daysAgo: 'ọjọ sẹyin',
    total: 'lapapọ',
    maybeLater: 'Boya Lẹẹkansi'
  },
  ig: {
    // Transactions specific translations
    transactionHistory: 'Akụkọ Azụmahịa',
    loadingTransactions: 'Na-ebunye azụmahịa...',
    noTransactionsYet: 'Enweghị azụmahịa ọ bụla',
    transactionsWillAppear: 'Akụkọ azụmahịa gị ga-apụta ebe a',
    transactionDetails: 'Nkọwa Azụmahịa',
    type: 'Ụdị',
    asset: 'Akụ',
    amount: 'Ọnụọgụ',
    value: 'Uru',
    date: 'Ụbọchị',
    status: 'Ọnọdụ',
    description: 'Nkọwa',
    fromAddress: 'Adreesị Site na',
    transactionFee: 'Ụgwọ Azụmahịa',
    
    // Transaction types
    sent: 'Ezipụla',
    received: 'Anatara',
    swapped: 'Agbanweela',
    mined: 'Egwupụtala',
    crypto: 'Crypto',
    
    // Status types
    completed: 'Emechara',
    pending: 'Na-echere',
    failed: 'Dara',
    
    // Date formats
    unknownDate: 'Ụbọchị amaghị',
    invalidDate: 'Ụbọchị na-ezighi ezi',

    // Wallets specific translations
    yourWallets: 'Akpa Ego Gị',
    loadingYourAssets: 'Ị na-ebunye akụ gị...',
    withdraw: 'Wepụ',
    requestWithdrawal: 'Rịọ Mwepụ',
    receive: 'Nata',
    generating: 'Na-emepụta...',
    exploreDeFi: 'Chọpụta Ohere DeFi',
    discoverTokens: 'Chọpụta tokens ọhụrụ na ugbo na-akpata nnukwu uru na gburugburu anyị.',
    exploreNow: 'Chọpụta Ugbu a',
    adminPrivilegesEnabled: 'Agbanyere ikike nchịkwa',
    loadingUserData: 'Na-ebunye data onye ọrụ...',
    minimumBalanceMet: 'Emezuru ihe achọrọ ego kacha nta ($6000+)',
    depositHistoryVerified: 'E nyochala akụkọ nkwụnye ego',
    withdrawalRequirements: 'Chọrọ ego kacha nta nke $6000 ma ọ bụ akụkọ nkwụnye ego. Kpọtụrụ nlekọta ndị ahịa maka nduzi.',
    contactSupport: 'Kpọtụrụ Nkwado',
    errorLoadingWalletData: 'Njehie ibunye data akpa ego',
    newAddressGenerated: 'Emepụtara adreesị {coin} ọhụrụ!',
    errorGeneratingAddress: 'Njehie nịmepụta adreesị akpa ego',
    sentSuccessfully: 'Ezipụla nke ọma!',
    addressCopied: 'Edepụtara adreesị!',
    noAddressFound: 'Ahụghị adreesị ọ bụla maka mkpụrụ ego a',
    
    // Modal translations
    send: 'Zipụ',
    withdrawalRequirements: 'Ihe Achọrọ Mwepụ',
    recipientAddress: 'Adreesị Onye Nnata',
    enterAddress: 'Tinye adreesị {symbol}',
    amountUSD: 'Ọnụọgụ (USD)',
    confirmSend: 'Kwenye Izipụ',
    withdrawalRequirementsDescription: 'Iji nweta ike ịwepụ, ịkwesịrị imezu otu n\'ime ọnọdụ ndị a:',
    minimumBalanceRequirement: '• Jigide ego kacha nta nke $6,000 USD ma ọ bụrụ na ị bụ onye na-egwupụta ihe',
    makeDepositRequirement: '• Kwụnye ego n\'akpa ego gị',
    withdrawalAssistance: 'Ọ bụrụ na ịchọrọ enyemaka ma ọ bụ nwee ajụjụ gbasara amụma mwepụ anyị, biko kpọtụrụ ndị otu nlekọta ndị ahịa anyị na nkata dị n\'okpuru.',
    close: 'Mechie',
    shareAddressToReceive: 'Kekọrịta adreesị gị iji nata {coin}.',
    generatingAddress: 'Na-emepụta adreesị...',
    noAddressAvailable: 'Enweghị adreesị dị',
    copyAddress: 'Detuo Adreesị',
    
    // Form validation
    recipientAddressEmpty: 'Adreesị onye nnata enweghị ike ịdị ohere.',
    enterValidAmount: 'Biko tinye ọnụọgụ ziri ezi dị mma.',
    insufficientFunds: 'Ego ezughị oke maka azụmahịa a.',

    // Sidebar
    overview: 'Nchịkọta',
    wallets: 'Akpa Ego',
    transactions: 'Azụmahịa',
    mine: 'Ngwuputa',
    profile: 'Profaịlụ',
    settings: 'Ntọala',
    logout: 'Pụọ',
    language: 'Asụsụ',
    selectLanguage: 'Họrọ Asụsụ',
    
    // Common
    welcome: 'Nnọọ',
    loading: 'Ị na-ebunye...',
    save: 'Chekwaa',
    cancel: 'Kagbuo',
    confirm: 'Kwenye',
    delete: 'Hichapụ',
    edit: 'Dezie',
    
    // Overview page
    hello: 'Ndewo',
    readyToBook: 'Dịla njikere ịgbazinye njem gị na-esote na Lagos?',
    myWallet: 'Akpa Ego M',
    totalRides: 'Ngụkọta Ụgbọ',
    rating: 'Ogo',
    promoCodes: 'Koodu Nkwalite',
    findRide: 'Chọta Ụgbọ na Lagos',
    enterDestination: 'Tinye ebe ọ bụla na Lagos...',
    findRides: 'Chọta Ụgbọ',
    findingRides: 'Na-achọ Ụgbọ...',
    quickActions: 'Ọrụ Ngwa Ngwa',
    bookNewRide: 'Tinye Ụgbọ Ọhụrụ',
    scheduleForLater: 'Hazie Maka Oge Ọzọ',
    recentTrips: 'Njem Na-adịbeghị Anya',
    
    // Mine page
    cryptoMining: 'Ngwuputa Crypto',
    miningDescription: 'Malite ngwuputa akụ iji mee ka ngụkọta akpa ego gị dịkwuo elu. Ngwuputa bụ ihe atụ ma na-arụ ọrụ naanị mgbe ị nọ na ibe a. Maka Ngwuputa Ọsọ, Kpọtụrụ ndị na-elekọta anyị maka nduzi',
    activeMiners: 'Ndị Na-egwupụta Ọrụ',
    totalMinedValue: 'Ngụkọta Uru Egwupụtara',
    totalCoinsMined: 'Ngụkọta Mkpụrụ ego Egwupụtara',
    hashRate: 'Ọnụego Hash',
    price: 'Ọnụahịa',
    loginToMine: 'Banye iji Gwupụta',
    stopMining: 'Kwụsị Ngwuputa',
    startMining: 'Malite Ngwuputa',
    pleaseLoginToMine: 'Biko banye iji malite ngwuputa',
    howMiningWorks: 'Ka Ngwuputa si Arụ Ọrụ',
    miningInstruction1: 'Maka ngwuputa ọsọ kpọtụrụ ndị na-elekọta anyị ma ọ bụ ndị nnọchiteanya',
    miningInstruction2: 'Ngwuputa bụ ihe atụ ma na-arụ ọrụ naanị mgbe ị nọ na ibe a',
    miningInstruction3: 'Oge ngwuputa ọ bụla na-agbakwunye crypto ozugbo na akpa ego gị',
    miningInstruction4: 'A na-agbakwunye ego ndị a gbupụtara na akpa ego gị kpọmkwem yana ngụkọta ego',
    miningInstruction5: 'Ị nwere ike igwupụta ọtụtụ cryptocurrencies n\'otu oge',
    miningInstruction6: 'A na-echekwa azụmahịa kpọmkwem kwa sekọnd 30 maka oge ngwuputa na-arụ ọrụ',
    loadingMiningRigs: 'Na-ebunye ngwá ọrụ ngwuputa...',

    // New Overview page translations
    welcomeToPaycoin: 'Nnọọ na Paycoin',
    liveTransactions: 'Azụmahịa Ndụ',
    realTimeActivity: 'Ọrụ oge niile',
    liveUpdates: 'Mmelite ndụ',
    transactionsToday: 'azụmahịa taa',
    totalBalance: 'Ngụkọta Ego',
    portfolioChange24h: 'Mgbanwe Pọtụfoliyo 24h',
    bitcoinBalance: 'Ego Bitcoin',
    activities24h: 'Ọrụ 24h',
    aiTrading: 'Trading AI',
    automatedTradingDescription: 'Trading akpaghị aka na njikwa ihe egwu nwere ọgụgụ isi',
    risk: 'IHE EGWU',
    currentPrice: 'Ọnụahịa Ugbu a',
    h24Change: 'Mgbanwe 24h',
    riskLevel: 'Ọkwa Ihe Egwu',
    riskScore: 'Akara Ihe Egwu',
    analyze: 'Nyochaa',
    activateAITrading: 'Gbanye Trading AI',
    aiMarketAnalysis: 'Nyocha Ahịa AI',
    riskWarning: 'Ịdọ aka ná ntị Ihe Egwu',
    recommendedStrategy: 'Atụmatụ Akwadoro',
    highRiskStrategy: 'Tụlee nha ọnọdụ dị ntakịrị ma debe iwu nkwụsị-mfu siri ike. Lelee mgbanwe ahịa anya.',
    mediumRiskStrategy: 'Ghasa pọtụfoliyo gị ma tụlee nkezi ọnụ ahịa dollar. Debe ọkwa uru na nkwụsị-mfu.',
    lowRiskStrategy: 'Dabara maka nchịkọta nwayọ. Tụlee atụmatụ ijide ogologo oge na nhazigharị oge.',
    aiTradingActivated: 'Trading AI Agbanyere!',
    aiBotConnected: 'Bot trading AI gị ejikọla na',
    wallet: 'akpa ego gị',
    nextStep: 'Nzọụkwụ Ọzọ',
    depositFundsToStart: 'Tinye ego na',
    walletToGenerateProfits: 'akpa ego gị ka ịmalite iwepụta uru na trading nke AI na-akwado.',
    goToWallet: 'Gaa na Akpa Ego',
    aiStartTrading: 'AI gị ga-amalite trading na-akpaghị aka ozugbo enwere ego',
    startMiningNow: 'Malite Ngwuputa Ugbu a',
    putHardwareToWork: 'Tinye ngwaike gị nọrụ ma nweta ụgwọ ọrụ crypto.',
    startMining: 'Malite Ngwuputa',
    recentActivity: 'Ọrụ Na-adịbeghị Anya',
    viewAll: 'Lelee Ha Nile',
    noRecentActivity: 'Enweghị ọrụ na-adịbeghị anya',
    welcomeBonus: 'Bonus Nnabata',
    transaction: 'Azụmahịa',
    upgradeSecurity: 'Kwalite Nchekwa',
    enable2FADescription: 'Gbanwee Njirimara Abụọ Maka nchekwa ka mma.',
    secureAccount: 'Chekwaa Akaụntụ',
    mineEthereum: 'Gwuo Ethereum',
    mineEthereumDescription: 'Sonye na netwọk ma malite igwupụta crypto nke abụọ kachasị ukwuu.',
    viewAllTransactions: 'Lelee Azụmahịa Nile',
    viewTransactionHistory: 'Hụ akụkọ azụmahịa gị zuru ezu ma soro ọrụ gị niile.',
    viewHistory: 'Lelee Akụkọ Ihe Mere Eme',
    bonusAlreadyClaimed: 'Ekwupụtala Bonus!',
    claim50Bonus: 'Pịa bọtịnụ iji nweta $50 gị',
    bonusAlreadyClaimedDescription: 'Ị narịtala bonus nnabata gị. Lelee ego akpa ego gị!',
    claim50Description: 'Nweta $50 na BTC site na ịpị bọtịnụ UGbu a!',
    claiming: 'Na-azọrọ...',
    bonusClaimed: 'Ekwupụtala Bonus ✓',
    claim50Bitcoin: 'Nweta $50 na Bitcoin',
    failedToClaimBonus: 'Emechaghị ịnweta bonus',
    failedToClaimBonusTryAgain: 'Emechaghị ịnweta bonus. Biko nwaa ọzọ.',
    success: 'Ihe ịga nke ọma!',
    youHaveClaimed50: 'Ị nwetagoro $50 gị nke ọma!',
    bonusAddedDescription: 'Agbakwunyela $50 na ego gị yana BTC hà nhata na akpa ego Bitcoin gị.',
    great: 'Ọ dị mma!',
    justNow: 'Ugbu a',
    minutesAgo: 'nkeji gara aga',
    hoursAgo: 'awa gara aga',
    daysAgo: 'ụbọchị gara aga',
    total: 'ngụkọta',
    maybeLater: 'Eleghị anya ma emechaa'
  }
};

interface LanguageContextType {
  currentLanguage: string;
  setCurrentLanguage: (lang: string) => void;
  t: typeof translations.en;
  languages: typeof languages;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('preferred-language') || 'en';
    }
    return 'en';
  });

  const t = translations[currentLanguage as keyof typeof translations] || translations.en;

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('preferred-language', currentLanguage);
    }
  }, [currentLanguage]);

  const value = {
    currentLanguage,
    setCurrentLanguage: (lang: string) => {
      setCurrentLanguage(lang);
    },
    t,
    languages
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};