import React, { createContext, useState, useContext, useEffect, ReactNode } from 'react';

// Language configuration
export const languages = {
  en: {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    flag: '🇺🇸',
    dir: 'ltr' as const
  },
  es: {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    flag: '🇪🇸',
    dir: 'ltr' as const
  },
  fr: {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    flag: '🇫🇷',
    dir: 'ltr' as const
  },
  ha: {
    code: 'ha',
    name: 'Hausa',
    nativeName: 'Hausa',
    flag: '🇳🇬',
    dir: 'ltr' as const
  },
  yo: {
    code: 'yo',
    name: 'Yoruba',
    nativeName: 'Yorùbá',
    flag: '🇳🇬',
    dir: 'ltr' as const
  },
  ig: {
    code: 'ig',
    name: 'Igbo',
    nativeName: 'Igbo',
    flag: '🇳🇬',
    dir: 'ltr' as const
  }
};

// Global translations for the entire app
export const translations = {
  en: {
    // Sidebar
    overview: 'Overview',
    wallets: 'Wallets',
    transactions: 'Transactions',
    mine: 'Mine',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Logout',
    language: 'Language',
    selectLanguage: 'Select Language',
    
    // Common
    welcome: 'Welcome',
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    
    // Overview page
    hello: 'Hello',
    readyToBook: 'Ready to book your next ride in Lagos?',
    myWallet: 'My Wallet',
    totalRides: 'Total Rides',
    rating: 'Rating',
    promoCodes: 'Promo Codes',
    findRide: 'Find a Ride in Lagos',
    enterDestination: 'Enter any Lagos location...',
    findRides: 'Find Rides',
    findingRides: 'Finding Rides...',
    quickActions: 'Quick Actions',
    bookNewRide: 'Book a New Ride',
    scheduleForLater: 'Schedule for Later',
    recentTrips: 'Recent Trips',
    
    // Mine page
    cryptoMining: 'Crypto Mining',
    miningDescription: 'Start mining assets to increase your wallet balance. Mining is simulated and only active while you are on this page. For Faster Mining, Reach out to our customer care for guidance',
    activeMiners: 'Active Miners',
    totalMinedValue: 'Total Mined Value',
    totalCoinsMined: 'Total Coins Mined',
    hashRate: 'Hash Rate',
    mined: 'Mined',
    minedValue: 'Mined Value',
    price: 'Price',
    loginToMine: 'Login to Mine',
    stopMining: 'Stop Mining',
    startMining: 'Start Mining',
    pleaseLoginToMine: 'Please log in to start mining',
    howMiningWorks: 'How Mining Works',
    miningInstruction1: 'For faster Mining reach out to our customer care or Agents',
    miningInstruction2: 'Mining is simulated and only works while you are on this page',
    miningInstruction3: 'Each mining session adds crypto directly to your wallet',
    miningInstruction4: 'Mined amounts are added to both your specific wallet and total balance',
    miningInstruction5: 'You can mine multiple cryptocurrencies simultaneously',
    miningInstruction6: 'Transactions are auto-saved every 30 seconds for active mining sessions',
    loadingMiningRigs: 'Loading mining rigs...',

    // New Overview page translations
    welcomeToPaycoin: 'Welcome To Paycoin',
    liveTransactions: 'Live Transactions',
    realTimeActivity: 'Real-time user activity',
    liveUpdates: 'Live updates',
    transactionsToday: 'transactions today',
    totalBalance: 'Total Balance',
    portfolioChange24h: '24h Portfolio Change',
    bitcoinBalance: 'Bitcoin Balance',
    activities24h: '24h Activities',
    aiTrading: 'AI Trading',
    automatedTradingDescription: 'Automated trading with intelligent risk management',
    risk: 'RISK',
    currentPrice: 'Current Price',
    h24Change: '24h Change',
    riskLevel: 'Risk Level',
    riskScore: 'Risk Score',
    analyze: 'Analyze',
    activateAITrading: 'Activate AI Trading',
    aiMarketAnalysis: 'AI Market Analysis',
    riskWarning: 'Risk Warning',
    recommendedStrategy: 'Recommended Strategy',
    highRiskStrategy: 'Consider small position sizes and set strict stop-loss orders. Monitor market volatility closely.',
    mediumRiskStrategy: 'Diversify your portfolio and consider dollar-cost averaging. Set take-profit and stop-loss levels.',
    lowRiskStrategy: 'Suitable for gradual accumulation. Consider long-term holding strategy with periodic rebalancing.',
    aiTradingActivated: 'AI Trading Activated!',
    aiBotConnected: 'Your AI trading bot is now connected to your',
    wallet: 'wallet',
    nextStep: 'Next Step',
    depositFundsToStart: 'Deposit funds into your',
    walletToGenerateProfits: 'wallet to start generating profits with AI-powered trading.',
    goToWallet: 'Go to Wallet',
    aiStartTrading: 'Your AI will start trading automatically once funds are available',
    startMiningNow: 'Start Mining Now',
    putHardwareToWork: 'Put your hardware to work and earn crypto rewards.',
    startMining: 'Start Mining',
    recentActivity: 'Recent Activity',
    viewAll: 'View All',
    noRecentActivity: 'No recent activity',
    transactionsWillAppear: 'Your transactions will appear here',
    sent: 'Sent',
    received: 'Received',
    mined: 'Mined',
    crypto: 'Crypto',
    welcomeBonus: 'Welcome Bonus',
    swapped: 'Swapped',
    transaction: 'Transaction',
    completed: 'Completed',
    pending: 'Pending',
    failed: 'Failed',
    upgradeSecurity: 'Upgrade Your Security',
    enable2FADescription: 'Enable Two-Factor Authentication for enhanced protection.',
    secureAccount: 'Secure Account',
    mineEthereum: 'Mine Ethereum',
    mineEthereumDescription: 'Join the network and start mining the second-largest cryptocurrency.',
    viewAllTransactions: 'View All Transactions',
    viewTransactionHistory: 'See your complete transaction history and track all your activities.',
    viewHistory: 'View History',
    bonusAlreadyClaimed: 'Bonus Already Claimed!',
    claim50Bonus: 'Click the button to claim your $50',
    bonusAlreadyClaimedDescription: 'You have already received your welcome bonus. Check your wallet balance!',
    claim50Description: 'Get $50 in BTC by Clicking on the Button NOW!',
    claiming: 'Claiming...',
    bonusClaimed: 'Bonus Claimed ✓',
    claim50Bitcoin: 'Claim $50 worth of Bitcoin',
    failedToClaimBonus: 'Failed to claim bonus',
    failedToClaimBonusTryAgain: 'Failed to claim bonus. Please try again.',
    success: 'Success!',
    youHaveClaimed50: 'You have successfully claimed your $50!',
    bonusAddedDescription: '$50 has been added to your balance and equivalent BTC to your Bitcoin wallet.',
    great: 'Great!',
    justNow: 'Just now',
    minutesAgo: 'm ago',
    hoursAgo: 'h ago',
    daysAgo: 'd ago',
    unknownDate: 'Unknown date',
    invalidDate: 'Invalid date',
    total: 'total',
    maybeLater: 'Maybe Later'
  },
  es: {
    // Sidebar
    overview: 'Resumen',
    wallets: 'Billeteras',
    transactions: 'Transacciones',
    mine: 'Minar',
    profile: 'Perfil',
    settings: 'Configuración',
    logout: 'Cerrar Sesión',
    language: 'Idioma',
    selectLanguage: 'Seleccionar Idioma',
    
    // Common
    welcome: 'Bienvenido',
    loading: 'Cargando...',
    save: 'Guardar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    delete: 'Eliminar',
    edit: 'Editar',
    
    // Overview page
    hello: 'Hola',
    readyToBook: '¿Listo para reservar tu próximo viaje en Lagos?',
    myWallet: 'Mi Billetera',
    totalRides: 'Viajes Totales',
    rating: 'Calificación',
    promoCodes: 'Códigos Promo',
    findRide: 'Encuentra un Viaje en Lagos',
    enterDestination: 'Ingresa cualquier ubicación en Lagos...',
    findRides: 'Encontrar Viajes',
    findingRides: 'Buscando Viajes...',
    quickActions: 'Acciones Rápidas',
    bookNewRide: 'Reservar Nuevo Viaje',
    scheduleForLater: 'Programar para Después',
    recentTrips: 'Viajes Recientes',
    
    // Mine page
    cryptoMining: 'Minería de Cripto',
    miningDescription: 'Comienza a minar activos para aumentar tu saldo de billetera. La minería es simulada y solo está activa mientras estás en esta página. Para una minería más rápida, contacta a nuestro servicio al cliente para obtener orientación',
    activeMiners: 'Mineros Activos',
    totalMinedValue: 'Valor Total Minado',
    totalCoinsMined: 'Total de Monedas Minadas',
    hashRate: 'Tasa de Hash',
    mined: 'Minado',
    minedValue: 'Valor Minado',
    price: 'Precio',
    loginToMine: 'Iniciar Sesión para Minar',
    stopMining: 'Detener Minería',
    startMining: 'Comenzar Minería',
    pleaseLoginToMine: 'Por favor inicia sesión para comenzar a minar',
    howMiningWorks: 'Cómo Funciona la Minería',
    miningInstruction1: 'Para una minería más rápida contacta a nuestro servicio al cliente o Agentes',
    miningInstruction2: 'La minería es simulada y solo funciona mientras estás en esta página',
    miningInstruction3: 'Cada sesión de minería agrega cripto directamente a tu billetera',
    miningInstruction4: 'Las cantidades minadas se agregan tanto a tu billetera específica como al saldo total',
    miningInstruction5: 'Puedes minar múltiples criptomonedas simultáneamente',
    miningInstruction6: 'Las transacciones se guardan automáticamente cada 30 segundos para sesiones de minería activas',
    loadingMiningRigs: 'Cargando equipos de minería...',

    // New Overview page translations
    welcomeToPaycoin: 'Bienvenido a Paycoin',
    liveTransactions: 'Transacciones en Vivo',
    realTimeActivity: 'Actividad en tiempo real',
    liveUpdates: 'Actualizaciones en vivo',
    transactionsToday: 'transacciones hoy',
    totalBalance: 'Saldo Total',
    portfolioChange24h: 'Cambio de Portafolio 24h',
    bitcoinBalance: 'Saldo de Bitcoin',
    activities24h: 'Actividades 24h',
    aiTrading: 'Trading con IA',
    automatedTradingDescription: 'Trading automatizado con gestión inteligente de riesgos',
    risk: 'RIESGO',
    currentPrice: 'Precio Actual',
    h24Change: 'Cambio 24h',
    riskLevel: 'Nivel de Riesgo',
    riskScore: 'Puntuación de Riesgo',
    analyze: 'Analizar',
    activateAITrading: 'Activar Trading con IA',
    aiMarketAnalysis: 'Análisis de Mercado con IA',
    riskWarning: 'Advertencia de Riesgo',
    recommendedStrategy: 'Estrategia Recomendada',
    highRiskStrategy: 'Considere tamaños de posición pequeños y establezca órdenes de stop-loss estrictas. Monitoree la volatilidad del mercado de cerca.',
    mediumRiskStrategy: 'Diversifique su cartera y considere el promedio de costo en dólares. Establezca niveles de toma de ganancias y stop-loss.',
    lowRiskStrategy: 'Adecuado para acumulación gradual. Considere una estrategia de tenencia a largo plazo con reequilibrio periódico.',
    aiTradingActivated: '¡Trading con IA Activado!',
    aiBotConnected: 'Tu bot de trading con IA ahora está conectado a tu',
    wallet: 'billetera',
    nextStep: 'Próximo Paso',
    depositFundsToStart: 'Deposita fondos en tu',
    walletToGenerateProfits: 'billetera para comenzar a generar ganancias con trading potenciado por IA.',
    goToWallet: 'Ir a Billetera',
    aiStartTrading: 'Tu IA comenzará a operar automáticamente una vez que haya fondos disponibles',
    startMiningNow: 'Comenzar a Minar Ahora',
    putHardwareToWork: 'Pon tu hardware a trabajar y gana recompensas en cripto.',
    startMining: 'Comenzar a Minar',
    recentActivity: 'Actividad Reciente',
    viewAll: 'Ver Todo',
    noRecentActivity: 'Sin actividad reciente',
    transactionsWillAppear: 'Tus transacciones aparecerán aquí',
    sent: 'Enviado',
    received: 'Recibido',
    mined: 'Minado',
    crypto: 'Cripto',
    welcomeBonus: 'Bono de Bienvenida',
    swapped: 'Intercambiado',
    transaction: 'Transacción',
    completed: 'Completado',
    pending: 'Pendiente',
    failed: 'Fallido',
    upgradeSecurity: 'Mejorar Seguridad',
    enable2FADescription: 'Habilita la Autenticación de Dos Factores para una protección mejorada.',
    secureAccount: 'Proteger Cuenta',
    mineEthereum: 'Minar Ethereum',
    mineEthereumDescription: 'Únete a la red y comienza a minar la segunda criptomoneda más grande.',
    viewAllTransactions: 'Ver Todas las Transacciones',
    viewTransactionHistory: 'Ve tu historial completo de transacciones y rastrea todas tus actividades.',
    viewHistory: 'Ver Historial',
    bonusAlreadyClaimed: '¡Bono Ya Reclamado!',
    claim50Bonus: 'Haz clic en el botón para reclamar tus $50',
    bonusAlreadyClaimedDescription: 'Ya has recibido tu bono de bienvenida. ¡Revisa tu saldo de billetera!',
    claim50Description: '¡Obtén $50 en BTC haciendo clic en el botón AHORA!',
    claiming: 'Reclamando...',
    bonusClaimed: 'Bono Reclamado ✓',
    claim50Bitcoin: 'Reclamar $50 en Bitcoin',
    failedToClaimBonus: 'Error al reclamar bono',
    failedToClaimBonusTryAgain: 'Error al reclamar bono. Por favor, inténtalo de nuevo.',
    success: '¡Éxito!',
    youHaveClaimed50: '¡Has reclamado exitosamente tus $50!',
    bonusAddedDescription: '$50 se han agregado a tu saldo y BTC equivalente a tu billetera de Bitcoin.',
    great: '¡Genial!',
    justNow: 'Justo ahora',
    minutesAgo: 'm atrás',
    hoursAgo: 'h atrás',
    daysAgo: 'd atrás',
    unknownDate: 'Fecha desconocida',
    invalidDate: 'Fecha inválida',
    total: 'total',
    maybeLater: 'Quizás Más Tarde'
  },
  fr: {
    // Sidebar
    overview: 'Aperçu',
    wallets: 'Portefeuilles',
    transactions: 'Transactions',
    mine: 'Miner',
    profile: 'Profil',
    settings: 'Paramètres',
    logout: 'Se Déconnecter',
    language: 'Langue',
    selectLanguage: 'Choisir la Langue',
    
    // Common
    welcome: 'Bienvenue',
    loading: 'Chargement...',
    save: 'Sauvegarder',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    delete: 'Supprimer',
    edit: 'Modifier',
    
    // Overview page
    hello: 'Bonjour',
    readyToBook: 'Prêt à réserver votre prochain trajet à Lagos ?',
    myWallet: 'Mon Portefeuille',
    totalRides: 'Trajets Totaux',
    rating: 'Note',
    promoCodes: 'Codes Promo',
    findRide: 'Trouver un Trajet à Lagos',
    enterDestination: 'Entrez n\'importe quel endroit à Lagos...',
    findRides: 'Trouver des Trajets',
    findingRides: 'Recherche de Trajets...',
    quickActions: 'Actions Rapides',
    bookNewRide: 'Réserver un Nouveau Trajet',
    scheduleForLater: 'Planifier pour Plus Tard',
    recentTrips: 'Trajets Récents',
    
    // Mine page
    cryptoMining: 'Mining de Crypto',
    miningDescription: 'Commencez à miner des actifs pour augmenter votre solde de portefeuille. Le minage est simulé et uniquement actif lorsque vous êtes sur cette page. Pour un minage plus rapide, contactez notre service client pour obtenir des conseils',
    activeMiners: 'Mineurs Actifs',
    totalMinedValue: 'Valeur Totale Minée',
    totalCoinsMined: 'Total des Pièces Minées',
    hashRate: 'Taux de Hash',
    mined: 'Miné',
    minedValue: 'Valeur Minée',
    price: 'Prix',
    loginToMine: 'Se Connecter pour Miner',
    stopMining: 'Arrêter le Mining',
    startMining: 'Commencer le Mining',
    pleaseLoginToMine: 'Veuillez vous connecter pour commencer à miner',
    howMiningWorks: 'Comment Fonctionne le Mining',
    miningInstruction1: 'Pour un minage plus rapide, contactez notre service client ou nos Agents',
    miningInstruction2: 'Le minage est simulé et ne fonctionne que lorsque vous êtes sur cette page',
    miningInstruction3: 'Chaque session de minage ajoute de la crypto directement à votre portefeuille',
    miningInstruction4: 'Les montants minés sont ajoutés à la fois à votre portefeuille spécifique et au solde total',
    miningInstruction5: 'Vous pouvez miner plusieurs cryptomonnaies simultanément',
    miningInstruction6: 'Les transactions sont enregistrées automatiquement toutes les 30 secondes pour les sessions de minage actives',
    loadingMiningRigs: 'Chargement des équipements de minage...',

    // New Overview page translations
    welcomeToPaycoin: 'Bienvenue sur Paycoin',
    liveTransactions: 'Transactions en Direct',
    realTimeActivity: 'Activité en temps réel',
    liveUpdates: 'Mises à jour en direct',
    transactionsToday: 'transactions aujourd\'hui',
    totalBalance: 'Solde Total',
    portfolioChange24h: 'Changement de Portefeuille 24h',
    bitcoinBalance: 'Solde Bitcoin',
    activities24h: 'Activités 24h',
    aiTrading: 'Trading IA',
    automatedTradingDescription: 'Trading automatisé avec gestion intelligente des risques',
    risk: 'RISQUE',
    currentPrice: 'Prix Actuel',
    h24Change: 'Changement 24h',
    riskLevel: 'Niveau de Risque',
    riskScore: 'Score de Risque',
    analyze: 'Analyser',
    activateAITrading: 'Activer le Trading IA',
    aiMarketAnalysis: 'Analyse de Marché IA',
    riskWarning: 'Avertissement de Risque',
    recommendedStrategy: 'Stratégie Recommandée',
    highRiskStrategy: 'Envisagez des tailles de position réduites et définissez des ordres de stop-loss stricts. Surveillez attentivement la volatilité du marché.',
    mediumRiskStrategy: 'Diversifiez votre portefeuille et envisagez la moyenne de coût. Définissez des niveaux de prise de bénéfices et de stop-loss.',
    lowRiskStrategy: 'Convient pour une accumulation progressive. Envisagez une stratégie de détention à long terme avec rééquilibrage périodique.',
    aiTradingActivated: 'Trading IA Activé !',
    aiBotConnected: 'Votre bot de trading IA est maintenant connecté à votre',
    wallet: 'portefeuille',
    nextStep: 'Prochaine Étape',
    depositFundsToStart: 'Déposez des fonds dans votre',
    walletToGenerateProfits: 'portefeuille pour commencer à générer des profits avec le trading assisté par IA.',
    goToWallet: 'Aller au Portefeuille',
    aiStartTrading: 'Votre IA commencera à trader automatiquement une fois les fonds disponibles',
    startMiningNow: 'Commencer à Miner Maintenant',
    putHardwareToWork: 'Mettez votre matériel au travail et gagnez des récompenses en crypto.',
    startMining: 'Commencer à Miner',
    recentActivity: 'Activité Récente',
    viewAll: 'Voir Tout',
    noRecentActivity: 'Aucune activité récente',
    transactionsWillAppear: 'Vos transactions apparaîtront ici',
    sent: 'Envoyé',
    received: 'Reçu',
    mined: 'Miné',
    crypto: 'Crypto',
    welcomeBonus: 'Bonus de Bienvenue',
    swapped: 'Échangé',
    transaction: 'Transaction',
    completed: 'Terminé',
    pending: 'En Attente',
    failed: 'Échoué',
    upgradeSecurity: 'Améliorer la Sécurité',
    enable2FADescription: 'Activez l\'Authentification à Deux Facteurs pour une protection renforcée.',
    secureAccount: 'Sécuriser le Compte',
    mineEthereum: 'Miner Ethereum',
    mineEthereumDescription: 'Rejoignez le réseau et commencez à miner la deuxième plus grande cryptomonnaie.',
    viewAllTransactions: 'Voir Toutes les Transactions',
    viewTransactionHistory: 'Consultez votre historique complet de transactions et suivez toutes vos activités.',
    viewHistory: 'Voir l\'Historique',
    bonusAlreadyClaimed: 'Bonus Déjà Réclamé !',
    claim50Bonus: 'Cliquez sur le bouton pour réclamer vos 50$',
    bonusAlreadyClaimedDescription: 'Vous avez déjà reçu votre bonus de bienvenue. Vérifiez votre solde de portefeuille !',
    claim50Description: 'Obtenez 50$ en BTC en cliquant sur le bouton MAINTENANT !',
    claiming: 'En cours de réclamation...',
    bonusClaimed: 'Bonus Réclamé ✓',
    claim50Bitcoin: 'Réclamer 50$ en Bitcoin',
    failedToClaimBonus: 'Échec de la réclamation du bonus',
    failedToClaimBonusTryAgain: 'Échec de la réclamation du bonus. Veuillez réessayer.',
    success: 'Succès !',
    youHaveClaimed50: 'Vous avez réussi à réclamer vos 50$ !',
    bonusAddedDescription: '50$ ont été ajoutés à votre solde et l\'équivalent en BTC à votre portefeuille Bitcoin.',
    great: 'Super !',
    justNow: 'À l\'instant',
    minutesAgo: 'min',
    hoursAgo: 'h',
    daysAgo: 'j',
    unknownDate: 'Date inconnue',
    invalidDate: 'Date invalide',
    total: 'total',
    maybeLater: 'Peut-être Plus Tard'
  },
  ha: {
    // Sidebar
    overview: 'Duba',
    wallets: 'Walat',
    transactions: 'Maamaloli',
    mine: 'Hako',
    profile: 'Bayanin Kai',
    settings: 'Saituna',
    logout: 'Fita',
    language: 'Harshe',
    selectLanguage: 'Zaɓi Harshe',
    
    // Common
    welcome: 'Barka da zuwa',
    loading: 'Ana loda...',
    save: 'Ajiye',
    cancel: 'Soke',
    confirm: 'Tabbatar',
    delete: 'Share',
    edit: 'Gyara',
    
    // Overview page
    hello: 'Sannu',
    readyToBook: 'Shirye kake don yin haya a Lagos?',
    myWallet: 'Walati Na',
    totalRides: 'Jimlar Haya',
    rating: 'Kima',
    promoCodes: 'Lambobin Tallan',
    findRide: 'Nemo Haya a Lagos',
    enterDestination: 'Shigar da kowane wuri a Lagos...',
    findRides: 'Nemo Haya',
    findingRides: 'Ana Neman Haya...',
    quickActions: 'Ayyuka Maimaitawa',
    bookNewRide: 'Yi Sabon Haya',
    scheduleForLater: 'Shirya Don Gobe',
    recentTrips: 'Haya Kwanan Nan',
    
    // Mine page
    cryptoMining: 'Hakar Kudi na Sirri',
    miningDescription: 'Fara hakar kadarori don ƙara ma\'aunin walat ɗin ku. Hakar kwaikwayo ce kuma tana aiki ne kawai yayin da kuke kan wannan shafi. Don Hakar Sauri, Tuntuɓi kulawar abokin ciniki don jagora',
    activeMiners: 'Masu Haka Aiki',
    totalMinedValue: 'Jimlar Ƙimar Hakar',
    totalCoinsMined: 'Jimlar Kudaden da aka Haka',
    hashRate: 'Adadin Hash',
    mined: 'An Haka',
    minedValue: 'Ƙimar Hakar',
    price: 'Farashin',
    loginToMine: 'Shiga Don Haka',
    stopMining: 'Daina Hakar',
    startMining: 'Fara Hakar',
    pleaseLoginToMine: 'Don Allah shiga don fara hakar',
    howMiningWorks: 'Yadda Hakar ke Aiki',
    miningInstruction1: 'Don hakar sauri tuntuɓi kulawar abokin ciniki ko Wakilai',
    miningInstruction2: 'Hakar kwaikwayo ce kuma tana aiki ne kawai yayin da kuke kan wannan shafi',
    miningInstruction3: 'Kowane zaman haka yana ƙara kudin sirri kai tsaye zuwa walat ɗin ku',
    miningInstruction4: 'Adadin da aka haka ana ƙara su zuwa walat ɗin ku na musamman da jimlar ma\'auni',
    miningInstruction5: 'Kuna iya hakar kudaden sirri da yawa lokaci guda',
    miningInstruction6: 'Ana adana ma\'amaloli kai tsaye kowane daƙiƙa 30 don zaman hakar aiki',
    loadingMiningRigs: 'Ana loda kayan aikin hakar...',

    // New Overview page translations
    welcomeToPaycoin: 'Barka da zuwa Paycoin',
    liveTransactions: 'Ma\'amaloli Kai Tsaye',
    realTimeActivity: 'Ayyuka na lokaci gaskiya',
    liveUpdates: 'Sabuntawa kai tsaye',
    transactionsToday: 'ma\'amaloli yau',
    totalBalance: 'Jimlar Ma\'auni',
    portfolioChange24h: 'Canjin Fayil 24h',
    bitcoinBalance: 'Ma\'aunin Bitcoin',
    activities24h: 'Ayyuka 24h',
    aiTrading: 'Cinayar AI',
    automatedTradingDescription: 'Cinayar ta atomatik tare da sarrafa hadarin wayo',
    risk: 'HADARI',
    currentPrice: 'Farashin Na Yanzu',
    h24Change: 'Canjin 24h',
    riskLevel: 'Matakin Hadari',
    riskScore: 'Makin Hadari',
    analyze: 'Bincika',
    activateAITrading: 'Kunna Cinayar AI',
    aiMarketAnalysis: 'Binciken Kasuwa na AI',
    riskWarning: 'Gargadin Hadari',
    recommendedStrategy: 'Dabarar da Aka Ba da Shawara',
    highRiskStrategy: 'Yi la\'akari da ƙananan girman matsayi kuma saita umarnin dakatar da asara mai tsauri. Sa ido kan saurin canjin kasuwa sosai.',
    mediumRiskStrategy: 'Rarraba fayil ɗin ku kuma yi la\'akari da matsakaicin farashin dala. Saita matakan samun riba da dakatar da asara.',
    lowRiskStrategy: 'Ya dace don tarawa a hankali. Yi la\'akari da dabarun riƙe na dogon lokaci tare da daidaitawa na lokaci-lokaci.',
    aiTradingActivated: 'Cinayar AI An Kunna!',
    aiBotConnected: 'Bot ɗin cinayar AI ɗin ku yanzu yana haɗe da',
    wallet: 'walat ɗin ku',
    nextStep: 'Mataki Na Gaba',
    depositFundsToStart: 'Ajiye kuɗi a cikin',
    walletToGenerateProfits: 'walat ɗin ku don fara samar da riba tare da cinayar da AI ke tallafawa.',
    goToWallet: 'Je Walat',
    aiStartTrading: 'AI ɗin ku zai fara cinayar ta atomatik da zarar an sami kuɗi',
    startMiningNow: 'Fara Haka Yanzu',
    putHardwareToWork: 'Sanya kayan aikin ku yin aiki kuma ku sami ladan kuɗin sirri.',
    startMining: 'Fara Haka',
    recentActivity: 'Aiki Kwanan Nan',
    viewAll: 'Duba Duka',
    noRecentActivity: 'Babu aiki kwanan nan',
    transactionsWillAppear: 'Ma\'amalolin ku za su bayyana a nan',
    sent: 'Aika',
    received: 'Karɓa',
    mined: 'An Haka',
    crypto: 'Kudin Sirri',
    welcomeBonus: 'Kyautar Maraba',
    swapped: 'Canja',
    transaction: 'Ma\'amala',
    completed: 'An Kammala',
    pending: 'Ana Jira',
    failed: 'Ya Gaza',
    upgradeSecurity: 'Haɓaka Tsaro',
    enable2FADescription: 'Kunna Tabbatar da Abokan Biyu Don Ƙarin Kariya.',
    secureAccount: 'Tsare Asusu',
    mineEthereum: 'Haka Ethereum',
    mineEthereumDescription: 'Shiga cikin hanyar sadarwa kuma fara haka kudin sirri na biyu mafi girma.',
    viewAllTransactions: 'Duba Duk Ma\'amaloli',
    viewTransactionHistory: 'Dubi cikakken tarihin ma\'amalolin ku kuma ku bi duk ayyukan ku.',
    viewHistory: 'Duba Tarihi',
    bonusAlreadyClaimed: 'An riga an yi iƙirarin Kyauta!',
    claim50Bonus: 'Danna maɓallin don neman $50 ɗin ku',
    bonusAlreadyClaimedDescription: 'Kun riga kun karɓi kyautar maraba. Duba ma\'aunin walat ɗin ku!',
    claim50Description: 'Samu $50 a cikin BTC ta Danna Maɓallin YANZU!',
    claiming: 'Ana nema...',
    bonusClaimed: 'An yi iƙirarin Kyauta ✓',
    claim50Bitcoin: 'Yi iƙirarin $50 a cikin Bitcoin',
    failedToClaimBonus: 'Kasa yin iƙirarin kyauta',
    failedToClaimBonusTryAgain: 'Kasa yin iƙirarin kyauta. Don Allah a sake gwadawa.',
    success: 'Nasara!',
    youHaveClaimed50: 'Kun yi nasarar neman $50 ɗin ku!',
    bonusAddedDescription: 'An ƙara $50 zuwa ma\'aunin ku daidai da BTC zuwa walat ɗin ku na Bitcoin.',
    great: 'Mai Kyau!',
    justNow: 'Yanzu yanzu',
    minutesAgo: 'm da suka wuce',
    hoursAgo: 'h da suka wuce',
    daysAgo: 'k da suka wuce',
    unknownDate: 'Ranar da ba a sani ba',
    invalidDate: 'Ranar mara inganci',
    total: 'jimla',
    maybeLater: 'Wataƙila Daga Baya'
  },
  yo: {
    // Sidebar
    overview: 'Akopọ',
    wallets: 'Apamọwọ',
    transactions: 'Iṣẹṣiro',
    mine: 'Mi',
    profile: 'Profaili',
    settings: 'Etọ',
    logout: 'Jade',
    language: 'Ede',
    selectLanguage: 'Yan Ede',
    
    // Common
    welcome: 'Kaabo',
    loading: 'O n loọdu...',
    save: 'Fipamọ',
    cancel: 'Fagilee',
    confirm: 'Jẹrisi',
    delete: 'Paarẹ',
    edit: 'Ṣatunkọ',
    
    // Overview page
    hello: 'Pẹlẹ',
    readyToBook: 'Ṣetan lati yẹ iṣẹ rẹ ti o n bọ ni Lagos?',
    myWallet: 'Apamọwọ Mi',
    totalRides: 'Lapapọ Iṣẹ',
    rating: 'Iwọn',
    promoCodes: 'Awọn koodu Ipolongo',
    findRide: 'Wa Iṣẹ kan ni Lagos',
    enterDestination: 'Tẹ ibikibi ni Lagos...',
    findRides: 'Wa Awọn Iṣẹ',
    findingRides: 'N wa Awọn Iṣẹ...',
    quickActions: 'Awọn Iṣẹ Kia',
    bookNewRide: 'Yẹ Iṣẹ Tuntun',
    scheduleForLater: 'Yẹda Fun Lẹẹkansi',
    recentTrips: 'Awọn Iṣẹ Laipe',
    
    // Mine page
    cryptoMining: 'Gbigba Crypto',
    miningDescription: 'Bẹrẹ gbigba ẹru lati pọkun iwọn apamọwọ rẹ. Gbigba jẹ iṣẹlẹ atunṣe ati pe o nṣiṣẹ nikan nigbati o ba wa ni ojúewé yii. Fun Gbigba Yara, Darapọ mọ itọju onibara wa fun itọsọna',
    activeMiners: 'Awọn Olugba Ti nṣiṣẹ',
    totalMinedValue: 'Lapapọ Iye Gbigba',
    totalCoinsMined: 'Lapapọ Awọn Owo Gbigba',
    hashRate: 'Iwọn Hash',
    mined: 'Ti Gba',
    minedValue: 'Iye Gbigba',
    price: 'Iye',
    loginToMine: 'Wọle Lati Gba',
    stopMining: 'Duro Gbigba',
    startMining: 'Bẹrẹ Gbigba',
    pleaseLoginToMine: 'Jọwọ wọle lati bẹrẹ gbigba',
    howMiningWorks: 'Bawo ni Gbigba Ṣe nṣiṣẹ',
    miningInstruction1: 'Fun gbigba yara darapọ mọ itọju onibara wa tabi Awọn Aṣoju',
    miningInstruction2: 'Gbigba jẹ iṣẹlẹ atunṣe ati pe o nṣiṣẹ nikan nigbati o ba wa ni ojúewé yii',
    miningInstruction3: 'Gbogbo akoko gbigba nfi crypto taara si apamọwọ rẹ',
    miningInstruction4: 'Awọn iye ti a gba nfi kun apamọwọ rẹ pato ati lapapọ iwọn',
    miningInstruction5: 'O le gba ọpọlọpọ cryptocurrencies ni akoko kan',
    miningInstruction6: 'Awọn iṣẹṣiro nfipamọ taara ni gbogbo aaya 30 fun awọn akoko gbigba ti nṣiṣẹ',
    loadingMiningRigs: 'O n loọdu awọn ẹrọ gbigba...',

    // New Overview page translations
    welcomeToPaycoin: 'Kaabo si Paycoin',
    liveTransactions: 'Awọn Iṣẹṣiro Lailẹgbẹ',
    realTimeActivity: 'Iṣẹṣiro igba otitọ',
    liveUpdates: 'Awọn imudojuiwọn lailẹgbẹ',
    transactionsToday: 'awọn iṣẹṣiro loni',
    totalBalance: 'Lapapọ Iwọn',
    portfolioChange24h: 'Iyipada Portfolio 24h',
    bitcoinBalance: 'Iwọn Bitcoin',
    activities24h: 'Awọn Iṣẹ 24h',
    aiTrading: 'Titaja AI',
    automatedTradingDescription: 'Titaja aifọwọyi pẹlu iṣakoso ewu oye',
    risk: 'EWU',
    currentPrice: 'Iye Lọwọlọwọ',
    h24Change: 'Iyipada 24h',
    riskLevel: 'Ipele Ewu',
    riskScore: 'Iwọn Ewu',
    analyze: 'Ṣe iwadi',
    activateAITrading: 'Mu Titaja AI Ṣiṣẹ',
    aiMarketAnalysis: 'Iwadi Oja AI',
    riskWarning: 'Ikilo Ewu',
    recommendedStrategy: 'Ilana Imọran',
    highRiskStrategy: 'Ṣe akiyesi iwọn ipo kekere ki o fi awọn aṣẹ idaduro-padanu le ṣe. Ṣe abojuto iyipada oja ni ṣiṣe.',
    mediumStrategy: 'Yatọ portfolio rẹ ki o ṣe akiyesi apapọ iye dola. Fi awọn ipele gbigba-anfani ati idaduro-padanu ṣeto.',
    lowRiskStrategy: 'Yẹ fun ikunṣe diẹ diẹ. Ṣe akiyesi ilana titojọ igba-ọna pẹlu iṣọdọtun akoko.',
    aiTradingActivated: 'Titaja AI Ti Mu Ṣiṣẹ!',
    aiBotConnected: 'Bot titaja AI rẹ ti sopọ mọ',
    wallet: 'apamọwọ rẹ',
    nextStep: 'Igbesẹ Iwọle',
    depositFundsToStart: 'Fi awọn owo si',
    walletToGenerateProfits: 'apamọwọ rẹ lati bẹrẹ ṣiṣẹda ẹsan pẹlu titaja ti AI nṣe atilẹyin.',
    goToWallet: 'Lọ si Apamọwọ',
    aiStartTrading: 'AI rẹ yoo bẹrẹ titaja laifọwọyi ni kete ti owo ba wa',
    startMiningNow: 'Bẹrẹ Gbigba Ni Bayi',
    putHardwareToWork: 'Fi ẹrọ rẹ ṣiṣẹ ki o jẹ awọn ẹsan crypto.',
    startMining: 'Bẹrẹ Gbigba',
    recentActivity: 'Iṣẹ Laipe',
    viewAll: 'Wo Gbogbo',
    noRecentActivity: 'Ko si iṣẹ laipe',
    transactionsWillAppear: 'Awọn iṣẹṣiro rẹ yoo han nibi',
    sent: 'Ti firanṣẹ',
    received: 'Ti gba',
    mined: 'Ti Gba',
    crypto: 'Crypto',
    welcomeBonus: 'Bonusi Ikẹkọ',
    swapped: 'Ti paṣipaarọ',
    transaction: 'Iṣẹṣiro',
    completed: 'Ti pari',
    pending: 'Iṣẹyọ',
    failed: 'Ti kuna',
    upgradeSecurity: 'Ṣe agbekalẹ Aabo',
    enable2FADescription: 'Mu Ijẹrisi Meji Ṣiṣẹ Fun Aabo ti o ni ilọsiwaju.',
    secureAccount: 'Aabo Iroyin',
    mineEthereum: 'Gba Ethereum',
    mineEthereumDescription: 'Darapọ mọ nẹtiwọọki ki o bẹrẹ gbigba crypto keji tobi julọ.',
    viewAllTransactions: 'Wo Gbogbo Awọn Iṣẹṣiro',
    viewTransactionHistory: 'Wo itan iṣẹṣiro rẹ kikun ki o tẹle gbogbo awọn iṣẹ rẹ.',
    viewHistory: 'Wo Itan',
    bonusAlreadyClaimed: 'Bonusi Ti Gba Tẹlẹ!',
    claim50Bonus: 'Tẹ bọtini lati gba $50 rẹ',
    bonusAlreadyClaimedDescription: 'O ti gba bonusi ikẹkọ rẹ tẹlẹ. Ṣayẹwo iwọn apamọwọ rẹ!',
    claim50Description: 'Gba $50 ni BTC nipasẹ Tite Bọtini NI BAYI!',
    claiming: 'N gba...',
    bonusClaimed: 'Bonusi Ti Gba ✓',
    claim50Bitcoin: 'Gba $50 ni Bitcoin',
    failedToClaimBonus: 'Kuna lati gba bonusi',
    failedToClaimBonusTryAgain: 'Kuna lati gba bonusi. Jọwọ gbiyanju lẹẹkansi.',
    success: 'Aṣeyọri!',
    youHaveClaimed50: 'O ti gba $50 rẹ ni aṣeyọri!',
    bonusAddedDescription: 'A ti fi $50 kun iwọn rẹ ati Bitcoin dogba si apamọwọ Bitcoin rẹ.',
    great: 'Pẹlu!',
    justNow: 'Ni bayi',
    minutesAgo: 'iṣẹju sẹyin',
    hoursAgo: 'wakati sẹyin',
    daysAgo: 'ọjọ sẹyin',
    unknownDate: 'Ọjọ aimọ',
    invalidDate: 'Ọjọ ailọwọ',
    total: 'lapapọ',
    maybeLater: 'Boya Lẹẹkansi'
  },
  ig: {
    // Sidebar
    overview: 'Nchịkọta',
    wallets: 'Akpa Ego',
    transactions: 'Azụmahịa',
    mine: 'Ngwuputa',
    profile: 'Profaịlụ',
    settings: 'Ntọala',
    logout: 'Pụọ',
    language: 'Asụsụ',
    selectLanguage: 'Họrọ Asụsụ',
    
    // Common
    welcome: 'Nnọọ',
    loading: 'Ị na-ebunye...',
    save: 'Chekwaa',
    cancel: 'Kagbuo',
    confirm: 'Kwenye',
    delete: 'Hichapụ',
    edit: 'Dezie',
    
    // Overview page
    hello: 'Ndewo',
    readyToBook: 'Dịla njikere ịgbazinye njem gị na-esote na Lagos?',
    myWallet: 'Akpa Ego M',
    totalRides: 'Ngụkọta Ụgbọ',
    rating: 'Ogo',
    promoCodes: 'Koodu Nkwalite',
    findRide: 'Chọta Ụgbọ na Lagos',
    enterDestination: 'Tinye ebe ọ bụla na Lagos...',
    findRides: 'Chọta Ụgbọ',
    findingRides: 'Na-achọ Ụgbọ...',
    quickActions: 'Ọrụ Ngwa Ngwa',
    bookNewRide: 'Tinye Ụgbọ Ọhụrụ',
    scheduleForLater: 'Hazie Maka Oge Ọzọ',
    recentTrips: 'Njem Na-adịbeghị Anya',
    
    // Mine page
    cryptoMining: 'Ngwuputa Crypto',
    miningDescription: 'Malite ngwuputa akụ iji mee ka ngụkọta akpa ego gị dịkwuo elu. Ngwuputa bụ ihe atụ ma na-arụ ọrụ naanị mgbe ị nọ na ibe a. Maka Ngwuputa Ọsọ, Kpọtụrụ ndị na-elekọta anyị maka nduzi',
    activeMiners: 'Ndị Na-egwupụta Ọrụ',
    totalMinedValue: 'Ngụkọta Uru Egwupụtara',
    totalCoinsMined: 'Ngụkọta Mkpụrụ ego Egwupụtara',
    hashRate: 'Ọnụego Hash',
    mined: 'Egwupụtara',
    minedValue: 'Uru Egwupụtara',
    price: 'Ọnụahịa',
    loginToMine: 'Banye iji Gwupụta',
    stopMining: 'Kwụsị Ngwuputa',
    startMining: 'Malite Ngwuputa',
    pleaseLoginToMine: 'Biko banye iji malite ngwuputa',
    howMiningWorks: 'Ka Ngwuputa si Arụ Ọrụ',
    miningInstruction1: 'Maka ngwuputa ọsọ kpọtụrụ ndị na-elekọta anyị ma ọ bụ ndị nnọchiteanya',
    miningInstruction2: 'Ngwuputa bụ ihe atụ ma na-arụ ọrụ naanị mgbe ị nọ na ibe a',
    miningInstruction3: 'Oge ngwuputa ọ bụla na-agbakwunye crypto ozugbo na akpa ego gị',
    miningInstruction4: 'A na-agbakwunye ego ndị a gbupụtara na akpa ego gị kpọmkwem yana ngụkọta ego',
    miningInstruction5: 'Ị nwere ike igwupụta ọtụtụ cryptocurrencies n\'otu oge',
    miningInstruction6: 'A na-echekwa azụmahịa kpọmkwem kwa sekọnd 30 maka oge ngwuputa na-arụ ọrụ',
    loadingMiningRigs: 'Na-ebunye ngwá ọrụ ngwuputa...',

    // New Overview page translations
    welcomeToPaycoin: 'Nnọọ na Paycoin',
    liveTransactions: 'Azụmahịa Ndụ',
    realTimeActivity: 'Ọrụ oge niile',
    liveUpdates: 'Mmelite ndụ',
    transactionsToday: 'azụmahịa taa',
    totalBalance: 'Ngụkọta Ego',
    portfolioChange24h: 'Mgbanwe Pọtụfoliyo 24h',
    bitcoinBalance: 'Ego Bitcoin',
    activities24h: 'Ọrụ 24h',
    aiTrading: 'Trading AI',
    automatedTradingDescription: 'Trading akpaghị aka na njikwa ihe egwu nwere ọgụgụ isi',
    risk: 'IHE EGWU',
    currentPrice: 'Ọnụahịa Ugbu a',
    h24Change: 'Mgbanwe 24h',
    riskLevel: 'Ọkwa Ihe Egwu',
    riskScore: 'Akara Ihe Egwu',
    analyze: 'Nyochaa',
    activateAITrading: 'Gbanye Trading AI',
    aiMarketAnalysis: 'Nyocha Ahịa AI',
    riskWarning: 'Ịdọ aka ná ntị Ihe Egwu',
    recommendedStrategy: 'Atụmatụ Akwadoro',
    highRiskStrategy: 'Tụlee nha ọnọdụ dị ntakịrị ma debe iwu nkwụsị-mfu siri ike. Lelee mgbanwe ahịa anya.',
    mediumRiskStrategy: 'Ghasa pọtụfoliyo gị ma tụlee nkezi ọnụ ahịa dollar. Debe ọkwa uru na nkwụsị-mfu.',
    lowRiskStrategy: 'Dabara maka nchịkọta nwayọ. Tụlee atụmatụ ijide ogologo oge na nhazigharị oge.',
    aiTradingActivated: 'Trading AI Agbanyere!',
    aiBotConnected: 'Bot trading AI gị ejikọla na',
    wallet: 'akpa ego gị',
    nextStep: 'Nzọụkwụ Ọzọ',
    depositFundsToStart: 'Tinye ego na',
    walletToGenerateProfits: 'akpa ego gị ka ịmalite iwepụta uru na trading nke AI na-akwado.',
    goToWallet: 'Gaa na Akpa Ego',
    aiStartTrading: 'AI gị ga-amalite trading na-akpaghị aka ozugbo enwere ego',
    startMiningNow: 'Malite Ngwuputa Ugbu a',
    putHardwareToWork: 'Tinye ngwaike gị nọrụ ma nweta ụgwọ ọrụ crypto.',
    startMining: 'Malite Ngwuputa',
    recentActivity: 'Ọrụ Na-adịbeghị Anya',
    viewAll: 'Lelee Ha Nile',
    noRecentActivity: 'Enweghị ọrụ na-adịbeghị anya',
    transactionsWillAppear: 'Azụmahịa gị ga-apụta ebe a',
    sent: 'Ezipụla',
    received: 'Anatara',
    mined: 'Egwupụtala',
    crypto: 'Crypto',
    welcomeBonus: 'Bonus Nnabata',
    swapped: 'Agbanweela',
    transaction: 'Azụmahịa',
    completed: 'Emechara',
    pending: 'Na-echere',
    failed: 'Dara',
    upgradeSecurity: 'Kwalite Nchekwa',
    enable2FADescription: 'Gbanwee Njirimara Abụọ Maka nchekwa ka mma.',
    secureAccount: 'Chekwaa Akaụntụ',
    mineEthereum: 'Gwuo Ethereum',
    mineEthereumDescription: 'Sonye na netwọk ma malite igwupụta crypto nke abụọ kachasị ukwuu.',
    viewAllTransactions: 'Lelee Azụmahịa Nile',
    viewTransactionHistory: 'Hụ akụkọ azụmahịa gị zuru ezu ma soro ọrụ gị niile.',
    viewHistory: 'Lelee Akụkọ Ihe Mere Eme',
    bonusAlreadyClaimed: 'Ekwupụtala Bonus!',
    claim50Bonus: 'Pịa bọtịnụ iji nweta $50 gị',
    bonusAlreadyClaimedDescription: 'Ị narịtala bonus nnabata gị. Lelee ego akpa ego gị!',
    claim50Description: 'Nweta $50 na BTC site na ịpị bọtịnụ UGbu a!',
    claiming: 'Na-azọrọ...',
    bonusClaimed: 'Ekwupụtala Bonus ✓',
    claim50Bitcoin: 'Nweta $50 na Bitcoin',
    failedToClaimBonus: 'Emechaghị ịnweta bonus',
    failedToClaimBonusTryAgain: 'Emechaghị ịnweta bonus. Biko nwaa ọzọ.',
    success: 'Ihe ịga nke ọma!',
    youHaveClaimed50: 'Ị nwetagoro $50 gị nke ọma!',
    bonusAddedDescription: 'Agbakwunyela $50 na ego gị yana BTC hà nhata na akpa ego Bitcoin gị.',
    great: 'Ọ dị mma!',
    justNow: 'Ugbu a',
    minutesAgo: 'nkeji gara aga',
    hoursAgo: 'awa gara aga',
    daysAgo: 'ụbọchị gara aga',
    unknownDate: 'Ụbọchị amaghị',
    invalidDate: 'Ụbọchị na-ezighi ezi',
    total: 'ngụkọta',
    maybeLater: 'Eleghị anya ma emechaa'
  }
};

interface LanguageContextType {
  currentLanguage: string;
  setCurrentLanguage: (lang: string) => void;
  t: typeof translations.en;
  languages: typeof languages;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('preferred-language') || 'en';
    }
    return 'en';
  });

  const t = translations[currentLanguage as keyof typeof translations] || translations.en;

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('preferred-language', currentLanguage);
    }
  }, [currentLanguage]);

  const value = {
    currentLanguage,
    setCurrentLanguage: (lang: string) => {
      setCurrentLanguage(lang);
    },
    t,
    languages
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};